### ISSUE TITLE
Make ChemicalEnvironments more pythonic

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openff-toolkit#100]
Every time I look back at the `ChemicalEnvironements` code, I want to fix the way it handles the "getters" and "setters" and function naming to be more pythonic. 

As far as I know right now the only thing this is being used for is to check a SMIRKS pattern matches the section it is in using `getType`. Other than that function, @jchodera @davidlmobley is there any opposition to updating the internal structure and function naming here? 

This would be a good time to also make the `isValid` function independent of the SMIRKS parsing tool available so it can work with OEchem or RDKit.

**Comment by davidlmobley** [comment]
That's OK with me.

**Comment by jchodera** [comment]
This all sounds great!

I had to make some changes in `environment.py` in [the `Topology` PR](https://github.com/openforcefield/openforcefield/pull/86/files), so if you do start in on changes, you may first want to pull in the changes just to `environment.py` and then work from there.

**Comment by davidlmobley** [comment]
@bannanc can this be closed?

**Comment by bannanc** [comment]
No, I made some small fixes to parsing back in PR #108, but I haven't changed any of the code. I put this on the back burner thinking it didn't make sense to make large changes to this file while the topology branch wasn't merged. 

Then there was discussion in #145 and then an update in #200 about where `ChemicalEnvironments` should be stored since most of the functionality is only important in a tool like ChemPer that is trying to change SMIRKS patterns. That discussion made me more hesitant to make changes until it had a permanent home.
