### ISSUE TITLE
Consider spinning off a separate examples repository

### ISSUE THREAD

**Issue by slochower** [openforcefield/openff-toolkit#103]
I'm willing to help set this up, but we should probably discuss if it should still be under the main `openforcefield` umbrella and what sort of things should be shown.

**Comment by davidlmobley** [comment]
Short answers:
- Yes, still under `openforcefield`
- Probably should start with whatever examples we have that are research-level and accrete from there, as I don't think any of us at present has much developer time to go off and deliberately create a bunch of research-level examples
- One other concrete thing we could put there is code to run all of FreeSolv with smirnoff99Frosst, as that's a useful research-level example I have on hand.

**Comment by slochower** [comment]
Great. In the coming days, I'm going to test the conversion scripts on all the stuff in `benchmarksets` minus BRD4. Perhaps I should also test on FreeSolv.

**Comment by davidlmobley** [comment]
Awesome, sounds great. @andrrizzi is also adding more lysozyme stuff to benchmarksets so maybe touch bases with him/see his PR too.

**Comment by j-wags** [comment]
@andrrizzi and myself were considering this in a meeting yesterday. We decided it's best for now to keep examples in the main repo. However, we noted that:
* Some examples will require extra dependencies (eg. GROMACS)
* Some data files are large (`AlkEthOH` is 5 MB, even compressed), so we may want to move toward spinning off a data repo

**Comment by jchodera** [comment]
We can easily move example datasets to another repo (or S3) and add a convenience command to retrieve them.

Extra dependencies can be installed via %conda magic in Jupyter notebooks if we also go the route of converting all examples to notebooks.

https://hub.packtpub.com/ipython-7-3-releases-with-conda-and-pip-magics-and-python-3-8-compatibility/

**Comment by davidlmobley** [comment]
Yes, I'd go the route `alchemlyb` has gone and put larger datasets in a separate, conda-installable repo so the core toolkit remains lightweight but people can easily install the datasets if they need them.

**Comment by mattwthompson** [comment]
This is old and no action has been taken on it, so I'm going to close it (though I'll admit I prefer microrepos, including examples being separate from the core source code). As a half measure and convenience to users, we do have an examples package that copies the examples from the repo and pulls down a couple of extra dependencies:

```
$ conda install openff-toolkit-examples -c conda-forge
```

Of course if we do want to split examples out in the future we can! Let's just move the discussion and planning into a new issue.
