### ISSUE TITLE
Work with ParmEd to provide useful atom identifiers when converting to AMBER

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openff-toolkit#104]
To improve AMBER format support (via export to that format through ParmEd) we need to work with ParmEd to ensure that atoms end up with unique identifiers, e.g. as per https://github.com/openforcefield/smirnoff99Frosst/issues/76 .

**Comment by jchodera** [comment]
This issue should be migrated to the ParmEd issue tracker:
https://github.com/parmed/parmed/issues

**Comment by davidlmobley** [comment]
Our own atoms also need atom names for other reasons, e.g. #440

**Comment by mattwthompson** [comment]
Interchange has an implementation, which doesn't go through OpenMM or ParmEd, to ensure Amber files written from SMIRNOFF force fields and OpenFF objects get unique atom types while also trying to work against the atom type explosion problem. (Atom _names_, separately from _atom type names_, are also stored separately.) I think that's the issue being discussed here - of course re-open if I'm incorrect.
