### ISSUE TITLE
Mixup with conformer indices and ids in RDKitToolkitWrapper._elf_compute_rms_matrix

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-toolkit#1090]
**Describe the bug**

I think there was a bit of confusion as to whether conformer IDs were IDs or indices; they are IDs, i.e. labels. For the vast majority of the time, the IDs do correspond to indices; however, if the toolkit changes its implementation of `to_rdkit()` to not do this, the below code will abruptly stop working as intended.

https://github.com/openforcefield/openff-toolkit/blob/d39905b488850483c77de782db643af1a7ed1fb9/openff/toolkit/utils/rdkit_wrapper.py#L1178-L1191

**To Reproduce**

**Output**

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list` 

**Additional context**

**Comment by mattwthompson** [comment]
So the problem would be if conformers were given IDs (these IDs are an RDKit construct, on the rdmols?) of like `[4, 5, 6]` or anything non-sequential and not starting at 0 index?

**Comment by lilyminium** [comment]
Yup, precisely. For example:

```python
from rdkit import Chem
from rdkit.Chem import AllChem
mol = Chem.AddHs(Chem.MolFromSmiles("CCC"))
AllChem.EmbedMultipleConfs(mol)
print([conf.GetId() for conf in mol.GetConformers()])
```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```python
mol.RemoveConformer(0)
mol.RemoveConformer(4)
print([conf.GetId() for conf in mol.GetConformers()])
```
[1, 2, 3, 5, 6, 7, 8, 9]
