### ISSUE TITLE
`ToolkitRegistry.__repr__` causes strange rendering of `GLOBAL_TOOLKIT_REGISTRY` in docs

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1104]
**Describe the bug**
Some parts of the API docs show the repr of  `GLOBAL_TOOLKIT_REGISTRY`, which probably looks funny to those that don't happen to be familiar with how the repr works (#675 traces it back to yours truly). There are probably plenty of other places this or similar cases pop up; I'm just reporting one that stood out to me.

https://open-forcefield-toolkit.readthedocs.io/en/latest/api/generated/openff.toolkit.topology.Molecule.html#openff.toolkit.topology.Molecule.to_smiles

![image](https://user-images.githubusercontent.com/7935382/136398878-ff235ba7-d374-45c2-94f2-5559881b1897.png)

```python3
In [1]: from openff.toolkit.utils.toolkits import GLOBAL_TOOLKIT_REGISTRY

In [2]: GLOBAL_TOOLKIT_REGISTRY
Out[2]: ToolkitRegistry containing The RDKit, AmberTools, Built-in Toolkit
```

**To Reproduce**

**Output**

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list` 

**Additional context**

**Comment by Yoshanuikabundi** [comment]
Fixed in #1135 :grinning:
