### ISSUE TITLE
ChemicalEnvironments handle replacements with RDKit correctly

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openff-toolkit#111]
When I added support to `ChemicalEnvironments` for RDK, I couldn't find documentation for the replacement strings, but it turns out you can use them. 
Here's Greg addressing an issue I had run into while trying to parse SMARTS with replacement:
https://github.com/rdkit/rdkit/issues/1842#issuecomment-386337612

I will update the rdk_isValid function to use that functionality instead
https://github.com/openforcefield/openforcefield/blob/65f6b45954bde02c6cec1059661635c53a7f4e35/openforcefield/typing/chemistry/environment.py#L572

**Comment by mattwthompson** [comment]
I'm going to close this since [we're removing this module](https://github.com/openforcefield/openff-toolkit/issues/200#issuecomment-1387488094)
