### ISSUE TITLE
Molecule.to_hill_formula

### ISSUE THREAD

**Issue by richardjgowers** [openforcefield/openff-toolkit#1110]
`Molecule.to_hill_formula` is actually a staticmethod, taking a `Molecule`, whereas `Molecule.hill_formula` is the property which actually gives a Hill formula.  This is sort of ugly compared to all the other `to_X` methods.  If you're stlil at the point where you can break things, this would be a good option...

**Comment by j-wags** [comment]
I think we'd be OK to do this. A quick search for uses of these methods only yields internal packages:
* [Uses of `to_hill_formula`](https://github.com/search?q=to_hill_formula&type=code)
* [Uses of `hill_formula`](https://github.com/search?q=openff+%22.hill_formula%22&type=code) (filtered for openff specifically)

The GROMOS results in the second point seem to be distinct from our method -- They have a different attribute called `hill_formula` on some of their objects.
