### ISSUE TITLE
Inconsistent with force field as 2 words

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openff-toolkit#112]
The READMEs in this repository are still inconsistent about if force field is one word or two. The Mobley group has been using "force field" and I believe OpenFF agreed on this as well via Slack, but we should make sure we're consistent in our documentation and especially when we write our own name!

**Comment by j-wags** [comment]
Some guidelines:
* We should make sure the spacing is "Force field" anywhere in 
    * user-facing text (markdown and reStructuredText), 
    * jupyter notebook markdown blocks
    * python docstrings
    * mentions of the organization name ("Open Force Field")
* We should use the case-sensitive `ForceField` class name in direct references to the python class

This Issue can be closed when:
* A PR is merged where the git repo has been reviewed and instances of incorrect usage are fixed
