### ISSUE TITLE
How to override default charge assignment?

### ISSUE THREAD

**Issue by orioncohen** [openforcefield/openff-toolkit#1126]
I am currently attempting to parameterize the PF6- anion with the Sage force field:

```python
from openff.toolkit.typing.engines.smirnoff import ForceField
from openff.toolkit.topology import Molecule, Topology

pf6_minus = "F[P-](F)(F)(F)(F)F"

forcefield = ForceField("openff_unconstrained-2.0.0.offxml")
ethanol = Molecule.from_smiles(pf6_minus)
topology = Topology.from_molecules(molecules=[ethanol])
system = forcefield.create_openmm_system(topology)
```

but I am getting an `UnassignedMoleculeChargeException`.

```Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
[13:59:24] UFFTYPER: Warning: hybridization set to SP3 for atom 1
[13:59:24] UFFTYPER: Unrecognized charge state for atom: 1
/Users/orioncohen/miniconda3/envs/openmm/lib/python3.9/site-packages/openff/toolkit/typing/engines/smirnoff/parameters.py:4155: Warning: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name '' and SMILES '[F][P-]([F])([F])([F])([F])[F]', 'partial_charge_method': 'am1bcc', 'use_conformers': None, 'strict_n_conformers': False, 'normalize_partial_charges': True, '_cls': <class 'openff.toolkit.topology.molecule.FrozenMolecule'>}"
Available toolkits are: [ToolkitWrapper around The RDKit version 2021.03.5, ToolkitWrapper around AmberTools version 21.0, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around The RDKit version 2021.03.5 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1bcc' is not available from RDKitToolkitWrapper. Available charge methods are ['mmff94'] 
 ToolkitWrapper around AmberTools version 21.0 <class 'TypeError'> : 'NoneType' object is not iterable
 ToolkitWrapper around Built-in Toolkit version None <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : Partial charge method "am1bcc"" is not supported by the Built-in toolkit. Available charge methods are ['zeros', 'formal_charge']

  warnings.warn(str(e), Warning)
Traceback (most recent call last):
  File "/Users/orioncohen/projects/lowT/openmm/setup/testing_pf6.py", line 9, in <module>
    system = forcefield.create_openmm_system(topology)
  File "/Users/orioncohen/miniconda3/envs/openmm/lib/python3.9/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1348, in create_openmm_system
    parameter_handler.postprocess_system(system, topology, **kwargs)
  File "/Users/orioncohen/miniconda3/envs/openmm/lib/python3.9/site-packages/openff/toolkit/typing/engines/smirnoff/parameters.py", line 3944, in postprocess_system
    raise UnassignedMoleculeChargeException(msg)
openff.toolkit.typing.engines.smirnoff.parameters.UnassignedMoleculeChargeException: The following molecules did not have charges assigned by any ParameterHandler in the ForceField:
[F][P-]([F])([F])([F])([F])[F]
```

I have RESP fit charges for PF6-. Can I make `ForceField` use those parameters so it doesn't throw an error?

**Comment by mattwthompson** [comment]
> I have RESP fit charges that I can use instead of the defaults. Is there any way I can use those charges so that an error is not thrown?

Yes, you can use pre-specified charges for this using library charges. (I'll write up a quick snippet in a moment) We should probably have an example that demonstrates this.

**Comment by mattwthompson** [comment]
The quick-and-dirty approach is to assign your charges to the `Moleucle` object via its `partial_charges` setter and then instruct `ForceField.create_openmm_system` to use those parameters. Be aware this might be deprecated in the future  since it muddies the water of what a force field is intended to do (#806).

```python3
import numpy as np
from openmm import NonbondedForce, unit

from openff.toolkit.topology import Molecule
from openff.toolkit.typing.engines.smirnoff import ForceField

pf6_minus = Molecule.from_smiles("F[P-](F)(F)(F)(F)F")

# Assign partial charges from a list-like object - replace with numbers from your favorite method
pf6_minus.partial_charges = np.asarray([0, -1, 0, 0, 0, 0, 0]) * unit.elementary_charge

forcefield = ForceField("openff_unconstrained-2.0.0.offxml")
topology = pf6_minus.to_topology()

system = forcefield.create_openmm_system(topology, charge_from_molecules=[pf6_minus])

# Inspect the openmm.System object to see which charges 
# actually ended up on each particle
for force in system.getForces():
    if type(force) == NonbondedForce:
        for i in range(force.getNumParticles()):
            print(force.getParticleParameters(i)[0])
```

A more programmatic approach is to modify the force field itself to include your pre-specified charges. This method ([`LibraryChargeType.from_molecule`](https://open-forcefield-toolkit.readthedocs.io/en/0.10.1/api/generated/openff.toolkit.typing.engines.smirnoff.parameters.LibraryChargeHandler.html?highlight=library%20charges#openff.toolkit.typing.engines.smirnoff.parameters.LibraryChargeHandler.LibraryChargeType.from_molecule)) creates a parameter whose SMIRKS pattern is unique to your molecule and also contains those charges.

```python3
import numpy as np
from openmm import NonbondedForce, unit

from openff.toolkit.topology import Molecule
from openff.toolkit.typing.engines.smirnoff import ForceField
from openff.toolkit.typing.engines.smirnoff.parameters import LibraryChargeHandler

pf6_minus = Molecule.from_smiles("F[P-](F)(F)(F)(F)F")

# Assign partial charges from a list-like object
pf6_minus.partial_charges = np.asarray([0, -1, 0, 0, 0, 0, 0]) * unit.elementary_charge

library_charge_type = LibraryChargeHandler.LibraryChargeType.from_molecule(pf6_minus)

forcefield = ForceField("openff_unconstrained-2.0.0.offxml")
forcefield["LibraryCharges"].add_parameter(parameter=library_charge_type)

topology = pf6_minus.to_topology()

system = forcefield.create_openmm_system(topology)

# Inspect the openmm.System object to see which charges
# actually ended up on each particle
for force in system.getForces():
    if type(force) == NonbondedForce:
        for i in range(force.getNumParticles()):
            print(force.getParticleParameters(i)[0])
```

Either approach should produce the same result:
```
$ python library_charges.py
0.0 e
-1.0 e
0.0 e
0.0 e
0.0 e
0.0 e
0.0 e
```

Interchange should be able to process these objects as well:

```python3
# copy everything up to `system = forcefield.create_openmm_system`
...
from openff.interchange.components.interchange import Interchange
out = Interchange.from_smirnoff(force_field=forcefield, topology=topology)
out.to_whatever("file.txt")  # GROMACS, Amber, LAMMPS, etc.
```

but there may be some bugs; please carefully validate anything that Interchange exports if you use it in research work.

**Comment by orioncohen** [comment]
Thank you so much @mattwthompson! This is a way more thorough answer than I was hoping for. I hope this ends up in the documentation somewhere.

**Comment by mattwthompson** [comment]
cc: @Yoshanuikabundi

**Comment by orioncohen** [comment]
Follow up question on this @mattwthompson.

Usually RESP charges are associated with atoms in 3d space with no explicit bonding. I can infer a molecular graph from the XYZ coordinates and find an isomorphism between those atoms and the SMILEs string, but that would require that the SMILEs string has some canonical ordering of atoms.

Will OpenFF `SMILEs -> atom ordering` match other codes like `openbabel`? Alternatively, are there any well-established codes for matching xyz coordinates to the atom ordering generated by OpenFF? 

Obviously in the case of PF<sub>6</sub>, it's not too hard, but this will be a general issue for me. I'd be interested in contributing code to accomplish this if it hasn't already been done.

**Comment by lilyminium** [comment]
@orioncohen OpenFF outsources the SMILES interpretation to RDKit and OpenEye, if that helps. There is `Molecule.canonical_order_atoms` that again outsources it to RDKit and SMILES. The most foolproof way to order a smiles string would be to use mapped smiles and `Molecule.from_mapped_smiles`:

```python
>>> from openff.toolkit.topology.molecule import Molecule
>>> mol = Molecule.from_mapped_smiles("[C:3][N:2][O:1]")
>>> print([a.element.symbol for a in mol.atoms])
['O', 'N', 'C']
```

**Comment by orioncohen** [comment]
Thanks @lilyminium! I think that's enough information to cobble together a solution.

This is challenging because I have partial charge data from a RESP fit with no topology or guaranteed atom ordering, something like:
```
atom #    element    x    y    z    charge
0    P    0    0    0    +1 
1     F    1    0    0    -0.33
2    F    -1    0    0    -0.33
3    F    0    1    0    -0.33
4    F    0    -1    0    -0.33
5    F    0    0    1    -0.33
6    F    0    0    -1    -0.33
```

So I need to infer a map between the atom ordering in the partial charges and the atom ordering in the generated SMILE. I do think with the tools you linked this should be possible, if not already accomplished.

**Comment by lilyminium** [comment]
@orioncohen it sounds like you've got a handle on it -- if you're looking for other ways to infer a map with only coordinate and element data, MDAnalysis can convert into an RDKit molecule with an impressive bond guesser. e.g.

```
import MDAnalysis as mda
from openff.toolkit.topology.molecule import Molecule
u = mda.Universe("my.xyz")
rdmol = u.convert_to("RDKIT")  # preserves atom order
offmol = Molecule.from_rdkit(rdmol)   # preserves atom order
```

From there you can add your charges as above, or go directly to SMILES (not sure what you're working with):

```
smiles = offmol.to_smiles(mapped=True)
```

Or map to your SMILES with something like the below (not tested and might have the molecules the wrong way around):
```
pf6_minus = Molecule.from_smiles("F[P-](F)(F)(F)(F)F")
_, atom_map = Molecule.are_isomorphic(pf6_minus, offmol, return_atom_map=True)
reordered_charges = [my_charges[atom_map[i]] for i in range(len(charges))]
pf6_minus.charges = np.array(reordered_charges) * unit.elementary_charge
```

**Comment by orioncohen** [comment]
Awesome, that's exactly the functionality I was looking for. I had a feeling that someone had already solved this problem. Thanks so much for the detailed code.

**Comment by orioncohen** [comment]
Using the advice above, I was able to (nearly) solve this problem. I was hoping someone could answer one more question on this topic. When I iterate through partial charges and particles in the `system`, should I be guaranteed the same atom ordering as the `topology` that generated the system?

I am constructing a Topology with Parmed then using
```python
system = forcefield.create_openmm_system(topology)
```
to constuct the system. However when I iterate through the partial charges using @mattwthompson's code:
```python
for force in system.getForces():
    if type(force) == NonbondedForce:
        for i in range(force.getNumParticles()):
            print(force.getParticleParameters(i)[0])
```
or I iterate through the particle masses with:
```python
[system.getParticleMass(i) for i in range(system.getNumParticles()]
```
the partial charges and masses do not seem to have the same atom ordering as the original topology or as each other. Should they? It's also possible I am making a mistake in my code.

All of my unit tests have passed but when I tried writing regression tests that assumed the same atom ordering, they failed. So currently I am not sure if my code is even working as intended.

**Comment by j-wags** [comment]
Hm, that’s strange. The outputted system should have the same atom order as
the input topology. I’m also a little confused because you said the
topology came from parmed, but create_openmm_system should only accept
OpenFF topology objects as input. So maybe a wire is getting crossed
somewhere. Could you post your entire script?

**Comment by orioncohen** [comment]
Thanks @j-wags, some wires were definitely getting crossed. The System is inheriting the atom order from the Topology as intended. My mistake. As I stated above, however, Forces are not inheriting the atom ordering from System. To be more specific, I am getting a list of partial charges by calling:

```python
        for force in system.getForces():
            if type(force) == NonbondedForce:
                charge_array = np.zeros(force.getNumParticles())
                for i in range(len(charge_array)):
                    charge_array[i] = force.getParticleParameters(i)[0]._value
```
Since I assigned new partial charges, I know which partial charge corresponds to each atom. So I am using a dictionary to map from the partial charges back to the original atoms. Something like:
```python
partial_charges_to_atoms = {0.2: "atom0", -0.2 : "atom1", 0.2: "atom2", -0.2: "atom4"
atom_ordering_in_forces = [partial_charges_to_atoms[charge] for charge in charge_array]
```
I was expecting that the `atom_ordering_in_forces` would have the same atom ordering as the Topology and System, but it does not. Perhaps is not intended to? 

After writing this all out, I am increasingly thinking that my assumption was incorrect.

**Comment by lilyminium** [comment]
I'd maybe suggest not using a charge:atom mapping as different atoms might have the same charge, as in your example code shown.

Just following the discussion as I'd have also assumed that the openmm ordering followed the topology ordering.

**Comment by orioncohen** [comment]
Update, I believe that I found the error. In my attempt to support arbitrary permutations of atom ordering, I made some accidental arbitrary permutations. 

Iterating through Forces does follow the same Atom ordering and Topology and System.

Thank you for the help everyone and apologies for the mistake!
