### ISSUE TITLE
Convert utility scripts to modules and use entry_points instead for exposing to CLI

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#116]
https://github.com/openforcefield/openforcefield/tree/topology/utilities

**Comment by mattwthompson** [comment]
The `utilities/` folder has changed significantly over the past several years and I'm not sure anything in there is highly valuable as a CLI. If we do make a CLI in the future it might not be toolkit-specific and instead a sort of umbrella tool that delegates out to other packages (most of which did not exist in October 2018!).
