### ISSUE TITLE
Use importlib_metadata instead of pkg_resources to ensure compatibility with condacolab

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#1161]
**Describe the bug**
The OpenFF toolkit fails to find registered force fields when used with [condacolab](https://github.com/conda-incubator/condacolab) in google colab notebooks.

**To Reproduce**
See reproduction case in https://github.com/conda-incubator/condacolab/issues/20

**To fix**
The recommended scheme is now apparently [to use `importlib_metadata`](https://github.com/conda-incubator/condacolab/issues/20#issuecomment-1003342938).

We should update our usage (and perhaps our conda dependencies) to be more broadly compatible.

**Comment by j-wags** [comment]
Closed by #1163

**Comment by jchodera** [comment]
Thanks, everyone!
