### ISSUE TITLE
molecule.compute_partial_charges_am1bcc stuck?

### ISSUE THREAD

**Issue by mbatgh** [openforcefield/openff-toolkit#1237]
Hi,
I just tried to calculate charges for a non-peptide molecule - and my script took several hours to finish using four CPU nodes. Previously i did the same job for the same molecule using chimera (which also uses antechamber in ambertools) and it took only about 15mins on a single node. Also later in GAFFTemplateGenerator I provide a name for a cache file, but cannot find the resulting file anywhere, where is it gone?

Here:
https://github.com/openforcefield/openff-toolkit/issues/447
it says:
[If OpenEye Toolkit is not available] RDKit is used to assign a conformation, and antechamber -c bcc from the [AmberTools]](http://ambermd.org/AmberTools.php) distribution (which uses the sqm semiempirical quantum chemical package) is used to assign AM1-BCC charges.

this sounds as if by default only a single conformer was generated/used - if more than one conformer was generated and used this would explain why it takes so long here, but i could not find any documentation on that.

BTW: eventually i plan to do this for a number of molecules, and then save the topologies, so i can re-use them in subsequent multiple simulations of protein-ligand complexes with each of these ligands. Can anybody point me to a clear documentation for how to save the topologies/chages/FF parameters, and later re-use them, ideally in combination with different proteins? what is explained here:
https://github.com/openmm/openmmforcefields under "Using SystemGenerator to automate ..." sound like what I need, but how to use the code piece quoted below this caption is not obvious to me ... there is an object called "openmm_topology", and I do not understand where that comes from/how to generate it.

thanks for any help/advice!
Michael

**To Reproduce**
my script:
from openff.toolkit.topology import Molecule
from openmmforcefields.generators import GAFFTemplateGenerator
from openmm.app import ForceField
from openmm.app import PDBFile
from pdbfixer import PDBFixer
molecule = Molecule.from_file('5t35.sdf')
molecule.compute_partial_charges_am1bcc()
gaff = GAFFTemplateGenerator(cache='gaff-molecules.json', molecules=molecule, forcefield='gaff-2.11')
forcefield = ForceField('amber/protein.ff14SB.xml', 'amber/tip3p_standard.xml', 'amber/tip3p_HFE_multivalent.xml')
forcefield.registerTemplateGenerator(gaff.generator)
fixer = PDBFixer(filename='e3l-poi-5t35-DA.pdb')
fixer.findMissingResidues()
fixer.findNonstandardResidues()
fixer.replaceNonstandardResidues()
fixer.removeHeterogens(True)
fixer.findMissingAtoms()
fixer.addMissingAtoms()
fixer.addMissingHydrogens(7.0)
PDBFile.writeFile(fixer.topology, fixer.positions, open('test4-input.pdb', 'w'))
pdbfile = PDBFile('test4-input.pdb')
system = forcefield.createSystem(pdbfile.topology)

5t35.sdf is attached

**Computing environment (please complete the following information):**
 - Operating system Ubuntu 20.04.4 LTS 
 - Output of running `conda list` 
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
ambertools                21.12            py39hc630cb1_0    conda-forge
amberutils                21.0                     pypi_0    pypi
arpack                    3.7.0                hdefa2d7_2    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
boost                     1.74.0           py39h5472131_5    conda-forge
boost-cpp                 1.74.0               h9359b55_0    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.14.6           py39h400218f_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py39hf3d152e_0    conda-forge
conda-package-handling    1.7.3            py39h27cfd23_1  
cryptography              36.0.0           py39h9ce1e76_0  
cudatoolkit               10.2.89              h8f6ccaa_8    conda-forge
curl                      7.82.0               h7bff187_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.28          py39he80948d_0    conda-forge
docutils                  0.16             py39hf3d152e_3    conda-forge
expat                     2.4.7                h27087fc_0    conda-forge
fftw                      3.3.10          nompi_h77c792f_102    conda-forge
fontconfig                2.13.96              h8e229c2_2    conda-forge
fonttools                 4.31.2           py39hb9d737c_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
glib                      2.69.1               h4ff587b_1  
greenlet                  1.1.2            py39he80948d_1    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      3.3                pyhd3eb1b0_0  
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39hf3d152e_0    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.0            py39hf939315_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9  
libblas                   3.9.0           13_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libtiff                   4.2.0                h85742a9_0  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
libxslt                   1.1.33               hf705e74_1    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
llvm-openmp               12.0.1               h4bd325d_1    conda-forge
lxml                      4.8.0            py39hb9d737c_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.1            py39hb9d737c_0    conda-forge
matplotlib-base           3.5.1            py39h2fa2bec_0    conda-forge
mdtraj                    1.9.7            py39h138c130_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h7f8727e_2  
netcdf-fortran            4.5.4           nompi_h2b6e579_100    conda-forge
networkx                  2.7.1              pyhd8ed1ab_1    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numexpr                   2.8.0           py39hbd72853_101    conda-forge
numpy                     1.20.3           py39hdbf815f_1    conda-forge
numpydoc                  1.2                pyhd8ed1ab_0    conda-forge
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openff-forcefields        2.0.0              pyh6c4a22f_0    conda-forge
openff-toolkit            0.10.3             pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.10.3             pyhd8ed1ab_0    conda-forge
openmm                    7.7.0            py39h9717219_0    conda-forge
openmmforcefields         0.10.0             pyhd8ed1ab_0    conda-forge
openmoltools              0.8.8              pyhd8ed1ab_1    conda-forge
openssl                   1.1.1n               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            1.2.1rc0                 pypi_0    pypi
pandas                    1.4.1            py39hde0f152_0    conda-forge
parmed                    3.4.3            py39he80948d_1    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pdbfixer                  1.8.1              pyh6c4a22f_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    7.2.0            py39h6f3857e_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycairo                   1.21.0           py39h0934665_0    conda-forge
pycosat                   0.6.3            py39h27cfd23_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h06a4308_0  
pytables                  3.7.0            py39h2669a42_0    conda-forge
python                    3.9.5                h12debd9_4  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h3811e60_3    conda-forge
rdkit                     2021.09.5        py39h89e00b9_0    conda-forge
readline                  8.1.2                h7f8727e_1  
reportlab                 3.5.68           py39he59360d_1    conda-forge
requests                  2.27.1             pyhd3eb1b0_0  
ruamel_yaml               0.15.100         py39h27cfd23_0  
sander                    16.0                     pypi_0    pypi
scipy                     1.8.0            py39hee8e79c_1    conda-forge
setuptools                58.0.4           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.5.0              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_1    conda-forge
sqlalchemy                1.4.32           py39hb9d737c_0    conda-forge
sqlite                    3.37.0               hc218d9a_0  
tinydb                    4.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h1ccaba5_0  
tqdm                      4.62.3             pyhd3eb1b0_1  
tzdata                    2021e                hda174b7_0  
unicodedata2              14.0.0           py39h3811e60_0    conda-forge
urllib3                   1.26.7             pyhd3eb1b0_0  
xmltodict                 0.12.0                     py_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

**Additional context**
[5t35.sdf.gz](https://github.com/openforcefield/openff-toolkit/files/8380320/5t35.sdf.gz)

**Comment by mattwthompson** [comment]
Hi @mbatgh thanks for the detailed write-up!

> this sounds as if by default only a single conformer was generated/used

Correct. By default, without OpenEye tools available, one conformer is generated with RDKit and that conformer is passed to Antechamber. This is distinct from the [ELF10 variant](https://docs.eyesopen.com/toolkits/python/quacpactk/OEProtonClasses/OEAM1BCCELF10Charges.html) of AM1-BCC, which uses multiple conformers and is used [if OpenEye Toolkits and a license are found](https://openforcefield.github.io/standards/standards/smirnoff/#toolkitam1bcc-temporary-support-for-toolkit-based-am1-bcc-partial-charges). Conformer generation shouldn't be the bottleneck here, though. Even though it's a bit slow due to the size of the molecule, AM1BCC charges scale as the number of (heavy?) atoms cubed so that's going to be where the CPU spends most of its time.


```
In [1]: from openff.toolkit.topology import Molecule
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing

In [2]: molecule = Molecule.from_file('/Users/mwt/Downloads/5t35.sdf')

In [3]: %%timeit
   ...: molecule.generate_conformers(n_conformers=10)
   ...:
   ...:
10 s ± 802 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: molecule.n_atoms
Out[4]: 129
```

IIUC it's generally unadvisable to use AM1BCC on molecules of this size; OpenFF is working on some of tools to get around this limitation within our software stack but nothing is live yet. In general, assigning partial charges is the slowest step in our workflows, even for smaller molecules that don't take several minutes or hours. 

In any case, this is the command that's called under the hood to assign charges to this molecule:

```shell
$ antechamber -i 5t35.sdf -fi sdf -o charged.mol2 -fo mol2 -pf yes -dr n -c bcc -nc 0
```

I ran this for a few minutes on my little laptop - not long enough for the calculation to be completed, but enough to verify that it's not a quick calculation. If it takes a few hours then that's just the ground truth of using AM1BCC; if it takes closer to a few minutes then something else in your workflow is the bottleneck. I don't work on `openmmforcefields` so I'm not able to help much there, sorry!

Antechamber isn't parallelized so I wouldn't expect speedups from throwing a few cores at a single molecule.  I'm not familiar with how Chimera wraps Antechamber, so I don't know if there are any differences or shortcuts related to that comparison

**Comment by mbatgh** [comment]
Thanks, Matt, for the swift reply! 
The script i posted finishes in 3 seconds if I out-comment only the one line:
"molecule.compute_partial_charges_am1bcc()"
so this is what takes hours real-time
I also repeated the calculation for this structure saying:
antechamber -i 5t35.sdf -fi sdf -o charged.mol2 -fo mol2 -pf yes -dr n -c bcc -nc 0.0
using the ambertools (version 18) that comes with chimera, to find that this takes about as long - so, as you suspected
its really the semi-empirical AM1 optimization that just takes so long for this rather large molecule.
This being said, I'm fine with waiting some time - but i don't want to do this repeatedly when I set up more than one 
simulation run for the same molecule, so it would be good to understand how i can save, and re-use these
topologies (charges+FF parameters) once generated. The documentation is bit vague there...
cheers
Michael

**Comment by j-wags** [comment]
Hi @mbatgh,

You should be able to save the molecule with partial charges assigned to a new SDF, which can then be reloaded in the future (so you only need to calculate the partial charges once). For example:

```python
# Make a new molecule with no partial charges assigned
from openff.toolkit.topology import Molecule
mol = Molecule.from_smiles('CCO')
print(mol.partial_charges)
```
> None

```python
# Assign partial charges
mol.compute_partial_charges_am1bcc()
print(mol.partial_charges)
```
> [-0.13610011111111114 0.12639988888888887 -0.5998001111111111 0.04236688888888887 0.04236688888888887 0.04236688888888887 0.04319988888888887 0.04319988888888887 0.3959998888888889] e

```python
# Write the molecule to an SDF file, then load it and show that the charges are still there
mol.to_file('ethanol_with_charges.sdf', file_format='sdf')
mol_from_sdf = Molecule.from_file('ethanol_with_charges.sdf')
print(mol_from_sdf.partial_charges)
```
> [-0.13610011111111114 0.12639988888888887 -0.5998001111111111 0.04236688888888887 0.04236688888888887 0.04236688888888887 0.04319988888888887 0.04319988888888887 0.3959998888888889] e

**Comment by mbatgh** [comment]
see also https://github.com/openmm/openmm/issues/3539
