### ISSUE TITLE
Serialize numeric arrays efficiently

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#124]
Potentially large numeric arrays (eg. `Molecule` _conformers) will default to be serialized as strings of floats. This is inefficient, but not critically so. In the future, it would be good to update `Molecule.to_dict` and `Molecule.from_dict` with more efficient serializing means. 

Daniel Smith at MolSSI recommended using `numpy.ndarray.tobytes()`. As I understand it, this will give us a more efficient representation of the numeric array as a string (strings are JSON core primitives[1], which is a good thing for generality).

The exact method we should use is an open question. Some factors to consider:
- Does relying on the output of `numpy.ndarray.tobytes()` tie us to Python/numpy when reading files?
- Does `tobytes()` lose information about the original array shape?
- Where should we store units? Can we assume it's always `simtk.unit.angstrom` (which is what I'm implementing as the internal standard), or should units get a separate field?
- Should the serialized data be human-readable?

### Example of size savings in string representations of position array
```
from simtk import unit
import numpy as np
n_atoms = 5
positions = unit.Quantity(np.random.random((n_atoms, 3)), unit.angstroms)
print('Size of tobytes', len(positions.tobytes()))
print('Size of original as string', len(str(positions)))
```

> Size of tobytes 120
> Size of original as string 182

[1] https://json-schema.org/latest/json-schema-core.html#rfc.section.4.2.1

**Comment by j-wags** [comment]
Other potential leads from Daniel:
Pydantic -- https://github.com/samuelcolvin/pydantic
Marshmellow --https://github.com/marshmallow-code/marshmallow

**Comment by j-wags** [comment]
Pinging @dgasmith on this issue.

**Comment by j-wags** [comment]
My first attempt at serialization is in commit https://github.com/openforcefield/openforcefield/commit/11b71c413a5f1487e364085fdaa28f6675d3fd6f

Serialization function at line https://github.com/openforcefield/openforcefield/commit/11b71c413a5f1487e364085fdaa28f6675d3fd6f#diff-7e940574762b4c5280bc73250062806aR87

The logic is used in line https://github.com/openforcefield/openforcefield/commit/11b71c413a5f1487e364085fdaa28f6675d3fd6f#diff-dcc45fa83688f86668e384f78c5ab22aR1368

**Comment by dgasmith** [comment]
As a note, doing it with `np.dump` ensures you are locked into NumPy. Something like:

```
{
  "shape": arr.shape,
  "data": arr.tobytes()
}
```

allows the possibility of other languages to pick it up.

**Comment by j-wags** [comment]
arr.tobytes implemented in commit https://github.com/openforcefield/openforcefield/pull/119/commits/b7f5b8fc2d25e1f19728cacaf3f64c492f2e7ac9

**Comment by mattwthompson** [comment]
Handled (for a while now, I think) in [`serialize_numpy`/`deserialize_numpy`](https://github.com/openforcefield/openff-toolkit/blob/0.10.2/openff/toolkit/utils/utils.py#L642-L692)
