### ISSUE TITLE
FrozenMolecule isn't Frozen

### ISSUE THREAD

**Issue by richardjgowers** [openforcefield/openff-toolkit#1241]
**Describe the bug**

`FrozenMolecule` isn't very frozen (immutable).

From the docs:
```
Returns the list of conformers for this molecule. This returns a list of openmm.unit.Quantity-wrapped numpy
    arrays, of shape (3 x n_atoms) and with dimensions of distance. The return value is the actual list of
    conformers, and changes to the contents affect the original FrozenMolecule
```
Which seems right in the code too, there's just a return of the reference to the numpy array.

The `__hash__` just seems to return the smiles, so I'm assuming this is the frozen part of the Molecule and other attributes are still mutable?

As context, we were looking at subclassing this to provide an immutable object with a slightly different hash/eq and auditing its behaviour.

**Comment by j-wags** [comment]
Hi @richardjgowers 

That's right - A `FrozenMolecule` is foremost a graph molecule. It is "Frozen" in that the user can't add atoms or bonds. The "defining identity" of a  `FrozenMolecule`, for most operations, is: 

* atom elements
* atom formal charges
* atom stereochemistry
* atom is_aromatic
* bond connectivity
* bond orders
* bond stereochemistry
* bond is_aromatic
 
Attributes like `conformers` and `partial_charges` are mutable. They are also considered to be optional fields ("stuff that might have been loaded, coincidentally, with this important graph molecule"). So in our behavior, these fields are ignored by default and the information in them must be specifically be requested (for example `offmol.compute_partial_charges` ignores existing conformers unless the `use_conformers=...` kwarg is set).

**Comment by richardjgowers** [comment]
Ok thanks, I think this isn't an issue then
