### ISSUE TITLE
Unassigned angle/torsion parameter

### ISSUE THREAD

**Issue by pavankum** [openforcefield/openff-toolkit#1256]
**Describe the bug**
I was looking into the [Gen3 torsions set](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-04-09-OpenFF-Gen3-Torsion-Set-v1.0), and there seems to be some chemical perception issue with Nitrogens in resonance cases, or "[#7X3+1]=" type. Here is a notebook with 59 such molecules where some pass through but some fail angle parameter assignment, or torsion parameter assignment. 

Charge assignment failures: 0
Angle assignment failures: 1
Proper torsion assignment failures: 13
Total failures:  14 out of  59

**To Reproduce**
Notebook here:
[nitrogen_failures.tar.gz](https://github.com/openforcefield/openff-toolkit/files/8475931/nitrogen_failures.tar.gz)
Pdf of notebook for easy molecule viewing:
[check_nitrogen_parameters.pdf](https://github.com/openforcefield/openff-toolkit/files/8475944/check_nitrogen_parameters.pdf)

**Comment by pavankum** [comment]
Making a note that new parameters with the smarts patterns "[#7X3+1]-[#6X4]" , "[#7X3+1]-[#7X3]" for central bonds in torsions, and "[#8X]=,:[#7X3+1]-[*]" for angle may cover these, until further discussion.

**Comment by mattwthompson** [comment]
Is this a new issue (finding some molecules that should be assigned parameters, but aren't) or a regression (an old version of the toolkit _did_ assign parameters, but recent versions aren't)?

**Comment by pavankum** [comment]
I think it is a new issue, mostly lack of parameters and not toolkit related.

**Comment by pavankum** [comment]
Do you think this should be on forcefield tracker instead of here?

**Comment by mattwthompson** [comment]
Wherever is best for you and the fitting team to keep track of reports of missing parameters - if that's here that's not a problem. I just wanted to determine if this was a bug in the code or not.

**Comment by pavankum** [comment]
Just making a note for some failures, since these may not be important chemistries we can try to modify the general parameters to catch them
- for molecules of type (failure for central bond [3,5])
![image](https://user-images.githubusercontent.com/16142894/163236016-8c44e06f-3785-4d15-b3b0-e2fdddd27b52.png)
   simple solution would be to make `t51: [*:1]-[#6X4:2]-[#7X3:3]-[*:4]" ` more general with the first and third bonds being more flexible ` [*:1]~[#6X4:2]-[#7X3:3]~[*:4]`. 
- for molecules of type (failure for central bond [8,6])
![image](https://user-images.githubusercontent.com/16142894/163235969-de070bd1-6519-4a28-b18e-938c55093605.png)
   `t138: "[*:1]~[#7X2:2]-[#7X3:3]~[*:4]"` to include `#7X4` as well in the third position, making it `"[*:1]~[#7X2:2]-[#7X3,#7X4:3]~[*:4]"`

**Comment by pavankum** [comment]
Closing this since it is not a toolkit issue.
