### ISSUE TITLE
Debug CM1 and CM2 charge methods for antechamber charge calculation

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#128]
CM1 and CM2 charge methods are failing in AmberToolsToolkitWrapper.compute_partial_charges. I don't think this is super high-priority because the bcc charge method seems to be working, but we should come back at some point and bring these online.

**Comment by davidlmobley** [comment]
I agree with you. These are not particularly recommended (in fact we'd recommend against them) so I don't particularly care about whether we get them working, and it's definitely not high priority.

**Comment by davidlmobley** [comment]
Probably we should start using a project board soon to sort issues/make them easier to find.

**Comment by mattwthompson** [comment]
There's been no movement on this and, as far as I can tell, no interest in using CM1 or CM2. If that changes or somebody wants this, please open a new issue and we can discuss how to go about implementing it.
