### ISSUE TITLE
`VirtualSiteHandler` cannot handle `None` keywords

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#1283]
**Describe the bug**

The converters in the `VirtualSiteHandler` introduced in #1252 do not correctly handle the case whereby `outOfPlaneAngle` or `inPlaneAngle` is `"None"` in a serialised force field as this value is passed into the converter as `"None"` rather than `None`.

**To Reproduce**

```
        force_field = ForceField()

        handler = force_field.get_parameter_handler("VirtualSites")
        handler.add_parameter(parameter=VirtualSiteMocking.bond_charge_parameter("[*:1][*:2]"))
        handler.add_parameter(parameter=VirtualSiteMocking.monovalent_parameter("[*:1][*:2][*:3]"))
        handler.add_parameter(parameter=VirtualSiteMocking.divalent_parameter("[*:2][*:1][*:3]", "once"))
        handler.add_parameter(parameter=VirtualSiteMocking.trivalent_parameter("[*:1][*:2][*:3][*:4]"))

        ForceField(force_field.to_string())
```

**Output**

```
        if not supports_out_of_plane_angle and value is not None:
>           raise SMIRNOFFSpecError(
                f"'{self.type}' sites do not support `outOfPlaneAngle`"
E               openff.toolkit.utils.exceptions.SMIRNOFFSpecError: 'BondCharge' sites do not support `outOfPlaneAngle`

```

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list` 

**Additional context**

**Comment by mattwthompson** [comment]
We expect this is fixed in the shortly-upcoming 0.10.6 release; if anybody comes across this issue please upgrade to that version or newer.
