### ISSUE TITLE
AM1 OE Charges Not Symmetrised

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#1287]
**Describe the bug**

By default the OE toolkit wrapper uses the default `OEAM1Charges` constructor which doesn't symmetrize charges. This contrasts for example the default `OEAM1BCCCharges` which does.

I found it surprising that the charges weren't symmetrized and would argue for this to be the default. 

**To Reproduce**

**Output**

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list` 

**Additional context**

**Comment by j-wags** [comment]
Ah, nice find. I didn't know about this. I agree this is unwanted, and it looks like we'll want to thread [the `symmetrize=True` kwarg](https://docs.eyesopen.com/toolkits/python/quacpactk/OEProtonClasses/OEAM1Charges.html#OEProton::OEAM1Charges::Constructors) into [the appropriate constructor in `openeye_wrapper`](https://github.com/openforcefield/openff-toolkit/blob/master/openff/toolkit/utils/openeye_wrapper.py#L2059-L2063).
