### ISSUE TITLE
Implement Psi4 partial charge / fractional bond order computation

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#132]
Create a ToolkitWrapper for Psi4 that can generate partial charges and fractional bond orders, similar to OpenEyeToolkitWrapper.

**Comment by mattwthompson** [comment]
Given that there's been no movement on this for a few years and also given the likelihood that we would not be able to deploy Psi4 alongside the toolkit with AmberTools, I'm going to close this as not planned. If we or wanted to make an external `Psi4Wrapper` we can revisit this. If somebody else wants to make such a tool externally, we'd be happy to help!
