### ISSUE TITLE
Split OpenEyeToolkitWrapper into license-based toolkits

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#133]
As licenses are sold piecewise by Openeye, it's possible that users will have Quacpac but not Omega. This ticket is to separate the functionality of each license into its own ToolkitWrapper.

As a future concern, we might consider how this could dovetail with the work on Fragmenter, which relies on OEDepict and OEGrapheme. Fragmenter will likely be a core part of the bespoke workflow, and we should start considering how an open-source alternative could run.

**Comment by mattwthompson** [comment]
https://github.com/openforcefield/openff-toolkit/pull/850 partially solves this problem without splitting all of `OpenEyeToolkitWrapper` apart; a user with i.e. Quacpac but not Omega should be able to use Quacpac-wrapping methods in our own toolkit without needing a license that includes Omega.

At this point, `OpenEyeToolkitWrapper` is a large enough class that I would be -1 on doing that without a significant driving force. Feel free to re-open if you disagree and/or there is context I'm missing, of course.
