### ISSUE TITLE
OSX ARM/M1 conda-forge install fails without giving any useful information

### ISSUE THREAD

**Issue by goraj** [openforcefield/openff-toolkit#1371]
**Describe the bug**
Conda installation fails without giving sufficient information to the user.

**Output**
```bash
(openmm) ➜  data conda config --set unsatisfiable_hints True
(openmm) ➜  data conda install -c conda-forge openff-toolkit
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

OS: OSX 12.1
conda 4.12.0 using Python 3.9.13

**Comment by ijpulidos** [comment]
I think the issue here is that we still don't have an `ambertools` conda-forge package for the M1 architecture, and this is a dependency of `openff-toolkit` conda package. As a less-than-ideal workaround I believe you can build and install `ambertools` from source, and also install `openff-toolkit` using `pip install .` (from cloned source repo). 

I know for a fact that having an `ambertools` conda-forge package is in the roadmap, so maybe this will be solved soon.

**Comment by mattwthompson** [comment]
Ivan is correct - the status of that migration can be tracked here: https://github.com/conda-forge/ambertools-feedstock/issues/77. IIUC this would be nice to have but installing everything through Rosetta works fine, so it's not been a critical need. There have been a few attempts at getting those builds online but nothing yet. If you or anybody else is familiar with cross-compiling I'm sure PRs over there would be welcome!

In the meantime, you might be able to force you distribution to use `osx-64` by [prepending](https://github.com/conda-forge/miniforge/issues/165#issuecomment-860233092) `CONDA_SUBDIR=osx-64` to whatever command you're running, i.e. some common commands from my shell history are like

```
$ CONDA_SUBDIR=osx-64 mamba env create --file devtools/conda-envs/test_env.yaml
$ CONDA_SUBDIR=osx-64 mamba install ambertools rdkit -c conda-forge
```

(reading the thread now I realize I can probably avoid this by just setting it in the config ... )

I use (and recommend) `mamba` but happen to use Miniconda as the distribution - it's probably the same for other conda distributions.

**Comment by mattwthompson** [comment]
Apologies again for the confusing error message, unfortunately we don't have any simple way of nudging conda to be more useful when reporting failures to users. To be honest I could only diagnose the issue by running into it myself in the past.

We have added a section to our FAQ on this, hopefully it is helpful for future Internet explorers traversing the world via Google: https://docs.openforcefield.org/projects/toolkit/en/stable/faq.html#im-having-troubles-installing-the-openff-toolkit-on-my-apple-silicon-mac

However please note that this might go out of date at some point - hopefully once AmberTools and friends are packaged on `osx-arm64` this won't be an issue at all!

Keywords: `osx-arm64`, M1 Mac, M2 Mac, Apple Silicon
