### ISSUE TITLE
`Topology.to_openmm` fails if an atom doesn't have a name and `ensure_unique_atom_names=False`

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#1375]
Just recording a bug I found in the existing behavior while writing these tests: `Topology.to_openmm(ensure_unique_atom_names=False)` will raise an exception from the guts of OpenMM if any atom name is `None`, such as when a molecule is initialized from a SMILES. Might be frustrating for a user who is combining molecules from lots of different places and doesn't want to risk losing atom names. A simple fix might just be to call `str()` on the atom name before passing it to OpenMM, so that missing atom names are rendered in the PDB as the string "None" 😂

_Originally posted by @Yoshanuikabundi in https://github.com/openforcefield/openff-toolkit/pull/1368#discussion_r951166198_

**Comment by Yoshanuikabundi** [comment]
As we discovered in our working session this morning - Looks like there's no way in the API for an atom name to have the value `None` - empty strings are used instead. So this is probably not a problem!

**Comment by mattwthompson** [comment]
I don't think this is an issue. Using 817563a06d8c583a66bea74df278b1eddbaa3124:


```python
In [1]: from openff.toolkit import Molecule

In [2]: Molecule.from_smiles("ClCCCl").to_topology().to_openmm(ensure_unique_atom_names=False)
Out[2]: <Topology; 1 chains, 1 residues, 8 atoms, 7 bonds>

In [3]: [a.name for a in Molecule.from_smiles("ClCCCl").atoms]
Out[3]: ['', '', '', '', '', '', '', '']

**Comment by mattwthompson** [comment]
And to be extra sure:

```python3
In [1]: from openff.toolkit import Molecule

In [2]: for a in Molecule.from_smiles("ClCCCl").atoms:
   ...:     a.name = None
   ...:
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Input In [2], in <cell line: 1>()
      1 for a in Molecule.from_smiles("ClCCCl").atoms:
----> 2     a.name = None

File ~/software/openff-toolkit/openff/toolkit/topology/molecule.py:444, in Atom.name(self, other)
    436 """
    437
    438 Parameters
   (...)
    441     The new name for this atom
    442 """
    443 if type(other) != str:
--> 444     raise Exception(
    445         f"In setting atom name. Expected str, received {other} (type {type(other)})."
    446     )
    447 self._name = other

Exception: In setting atom name. Expected str, received None (type <class 'NoneType'>).

**Comment by j-wags** [comment]
Yup - I agree. Thanks for the sanity check everyone!
