### ISSUE TITLE
Make AmberTools optional

### ISSUE THREAD

**Issue by peastman** [openforcefield/openff-toolkit#1383]
**Is your feature request related to a problem? Please describe.**
The conda installer marks AmberTools as a required dependency.  That makes it impossible to install on computers for which AmberTools is not available, such as Windows or ARM Macs.  The code doesn't actually require it.  If you install from source, it will just detect that AmberTools is not available and run without it.  It's only the conda package that creates this limitation.

**Describe the solution you'd like**
Modify the recipe to not require AmberTools as a dependency.  You can still specify `run_constrained` to ensure that if it's installed, it has to be a compatible version.

**Describe alternatives you've considered**
I saw the documentation was just updated to suggest installing under Rosetta on ARM Macs.  That requires the entire environment and everything in it to run under Rosetta, which isn't always practical, and at best makes everything slower.  For Windows I suppose the workaround would be to use WSL, but that also is not always a good solution.  I don't think there exists any solution for ARM Linux, except perhaps to install the entire thing inside a VM running in QEMU.

**Additional context**

**Comment by j-wags** [comment]
Hi @peastman,

We also offer the [`openff-toolkit-base` conda package,](https://anaconda.org/conda-forge/openff-toolkit-base/files) which doesn't require the AmberTools package and allows for more custom setups. Would this satisfy your needs?

**Comment by peastman** [comment]
Possibly, I didn't realize that existed.  What are the differences?

**Comment by j-wags** [comment]
The only difference is the dependencies - All of the OFF toolkit source code is in the `openff-toolkit-base` conda package. The `openff-toolkit` conda package just requires the `openff-toolkit-base` package as well as a few additional deps (like AmberTools).
<img width="1030" alt="Screen Shot 2022-08-26 at 2 35 40 PM" src="https://user-images.githubusercontent.com/16329175/186994258-0e3badd5-fcb0-4c79-ba93-b4949c34fbf5.png">

**Comment by peastman** [comment]
That should work then.  Thanks!
