### ISSUE TITLE
Hierarchy schemes are lost by `Topology.from_openmm`

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-toolkit#1386]
**Describe the bug**
If a molecule with hierarchy schemes is passed to the `unique_molecules` argument of `Topology.from_openmm()`, that molecule will not have hierarchy schemes in the produced topology. This means we still need `ensure_unique_atom_names=False` in the Toolkit Showcase.

**To Reproduce**
```python
from openff.toolkit.utils import get_data_file_path
from openff.toolkit import Molecule, Topology
from openmm.app import PDBFile

peptide_path = get_data_file_path("proteins/MainChain_ALA_ALA.pdb")
peptide = Molecule.from_polymer_pdb(peptide_path)
print(peptide.hierarchy_schemes)

pdb = PDBFile(peptide_path)
top = Topology.from_openmm(pdb.topology, unique_molecules=[peptide])
print(top.molecule(0).hierarchy_schemes)
```

**Output**
The first print gives `{'chains': HierarchyScheme with uniqueness_criteria '('chain_id',)', iterator_name 'chains', and 1 elements, 'residues': HierarchyScheme with uniqueness_criteria '('chain_id', 'residue_number', 'insertion_code', 'residue_name')', iterator_name 'residues', and 4 elements}`, while the second gives `{}`

**Computing environment (please complete the following information):**
 - Arch Linux
<details><summary>Output of conda list</summary>
<pre>
# packages in environment at /home/joshmitchell/Documents/openff/interchange/.soap/examples:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.2.0              pyhd8ed1ab_0    conda-forge
amberlite                 22.0                     pypi_0    pypi
ambertools                22.0            py310h3aec49d_2    conda-forge
amberutils                21.0                     pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arpack                    3.7.0                hdefa2d7_2    conda-forge
ase                       3.22.1             pyhd8ed1ab_1    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h83bc5f7_3    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
boltons                   21.0.0             pyhd8ed1ab_0    conda-forge
boost                     1.74.0          py310h7c3ba0c_5    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            ha61ee94_1012    conda-forge
certifi                   2022.6.15                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
cftime                    1.6.1                    pypi_0    pypi
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
cmiles-base               0.1.6              pyhd8ed1ab_2    conda-forge
coverage                  6.4.4                    pypi_0    pypi
cryptography              37.0.4                   pypi_0    pypi
cudatoolkit               11.2.2               hf4e28a0_8    jaimergp/label/unsupported-cudatoolkit-shim
cudnn                     8.4.1.50             hed8a83a_0    conda-forge
curl                      7.83.1               h7bff187_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.32                  pypi_0    pypi
cytoolz                   0.12.0                   pypi_0    pypi
dask                      2022.8.1           pyhd8ed1ab_2    conda-forge
dask-core                 2022.8.1           pyhd8ed1ab_0    conda-forge
dask-jobqueue             0.7.4              pyhd8ed1ab_0    conda-forge
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2022.8.1           pyhd8ed1ab_2    conda-forge
ele                       0.2.0              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
etils                     0.7.1              pyhd8ed1ab_0    conda-forge
executing                 0.10.0             pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
f90wrap                   0.2.7                    pypi_0    pypi
fftw                      3.3.10          nompi_ha7695d1_103    conda-forge
flask                     2.2.2              pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.37.1                   pypi_0    pypi
foyer                     0.11.1             pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hca18f0e_0    conda-forge
fsspec                    2022.7.1           pyhd8ed1ab_0    conda-forge
future                    0.18.2                   pypi_0    pypi
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2                    pypi_0    pypi
gmso                      0.7.2              pyhd8ed1ab_0    conda-forge
greenlet                  1.1.3                    pypi_0    pypi
gromacs                   2022.2          nompi_hca75aac_100    conda-forge
grpc-cpp                  1.46.4               hbad87ad_2    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
hdf4                      4.2.15               h9772cbc_4    conda-forge
hdf5                      1.12.2          nompi_h2386368_100    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4                   pypi_0    pypi
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intermol                  0.1                pyhd8ed1ab_0    conda-forge
ipykernel                 6.15.1             pyh210e3f2_0    conda-forge
ipython                   8.4.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.2              pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jax                       0.3.16             pyhd8ed1ab_0    conda-forge
jaxlib                    0.3.15                   pypi_0    pypi
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
jsonschema                4.14.0             pyhd8ed1ab_0    conda-forge
jupyter-core              4.11.1                   pypi_0    pypi
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310hff52083_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kim-api                   2.3.0                h0911212_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.3               h3790be6_0    conda-forge
lammps                    2022.6.23                pypi_0    pypi
lark-parser               0.12.0             pyhd8ed1ab_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20220623.0      cxx17_h48a1fff_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libhwloc                  2.8.0                h32351e8_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.3                h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_3    conda-forge
libnetcdf                 4.8.1           nompi_h21705cb_104    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_2    conda-forge
libpng                    1.6.37               h753d276_4    conda-forge
libprotobuf               3.20.1               h6239696_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h0e0dad5_3    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.14               h22db469_4    conda-forge
libxslt                   1.1.35               h8affb1d_0    conda-forge
libzip                    1.9.2                hc869a4a_1    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
llvmlite                  0.38.1                   pypi_0    pypi
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.1                    pypi_0    pypi
lz4                       4.0.0                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-base           3.5.3           py310h8d5ebf3_2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mbuild                    0.15.1             pyhd8ed1ab_0    conda-forge
mdtraj                    1.9.7                    pypi_0    pypi
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
mlip                      1.0                  ha87248a_2    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
mpc                       1.2.1                h9f54685_0    conda-forge
mpfr                      4.1.0                h9202a9a_1    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     4.0.2              h846660c_100    conda-forge
mpiplus                   v0.0.1          pyhd8ed1ab_1003    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msgpack                   1.0.4                    pypi_0    pypi
msgpack-python            1.0.4           py310hbf28c38_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
n2p2                      2.1.4           py310hbd49d13_2    conda-forge
nbclient                  0.6.7              pyhd8ed1ab_0    conda-forge
nbconvert                 7.0.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.0.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.0.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nbval                     0.9.6              pyh9f0ad1d_0    conda-forge
nccl                      2.14.3.1             h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.6.0           nompi_hc402ea5_100    conda-forge
netcdf4                   1.6.0                    pypi_0    pypi
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
nglview                   3.0.3              pyh8a188c0_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
numba                     0.55.2                   pypi_0    pypi
numexpr                   2.8.3                    pypi_0    pypi
numpy                     1.22.4                   pypi_0    pypi
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openeye-toolkits          2022.1.1                py310_0    openeye
openeye-toolkits-python3-linux-x64 2022.1.1                 pypi_0    pypi
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-evaluator          0.4.0rc2+1.g7230c0f          pypi_0    pypi
openff-forcefields        2.0.0              pyh6c4a22f_0    conda-forge
openff-interchange        0.2.0rc5+17.g64836d5          pypi_0    pypi
openff-toolkit            0.11.0rc3+27.g35e3ef23          pypi_0    pypi
openff-units              0.1.7              pyh6c4a22f_1    conda-forge
openff-utilities          0.1.5              pyh6c4a22f_0    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openmm                    7.7.0                    pypi_0    pypi
openmmtools               0.21.5             pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            1.2.3rc0                 pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
pandoc                    2.19.2               ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panedr                    0.5.2                      py_0    conda-forge
parmed                    3.4.3                    pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pbr                       5.10.0             pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pdb4amber                 22.0                     pypi_0    pypi
pdbfixer                  1.8.1              pyh6c4a22f_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0                    pypi_0    pypi
pint                      0.19.2             pyhd8ed1ab_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkg-config                0.29.2            h36c2ea0_1008    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycairo                   1.21.0                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.9.2                    pypi_0    pypi
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pymbar                    3.0.5                    pypi_0    pypi
pymsmt                    22.0                     pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
pytables                  3.7.0           py310hb60b9b2_2    conda-forge
pytest                    6.2.5                    pypi_0    pypi
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python-constraint         1.4.0                      py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.2.1                   pypi_0    pypi
quippy                    NOT-A-GIT-REPOSITORY          pypi_0    pypi
rdkit                     2022.03.5       py310h1c297d8_0    conda-forge
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
reportlab                 3.5.68                   pypi_0    pypi
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
sander                    22.0                     pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.3.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.40                   pypi_0    pypi
stack_data                0.4.0              pyhd8ed1ab_0    conda-forge
sympy                     1.10.1                   pypi_0    pypi
tables                    3.7.0                    pypi_0    pypi
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.15.0                   pypi_0    pypi
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.1                      pypi_0    pypi
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
uncertainties             3.1.7              pyhd8ed1ab_0    conda-forge
unicodedata2              14.0.0                   pypi_0    pypi
unyt                      2.9.2              pyhd8ed1ab_1    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
voro                      0.4.6                h924138e_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha56f1ee_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
</pre>
</details>

**Additional context**
None

**Comment by j-wags** [comment]
Because we know that OpenMM Topologies _always_ have residue and chain info, I kinda think that we should add our "default hierarchy scheme" to the resulting molecules whenever we run `Topology.from_openmm`. We could also consider adding the info from the `unique_molecule` instead, but if we're getting residue names and numbers from the OpenMM Topology, it's probably safe to assume that the default residue scheme is the least surprising. But I totally agree not adding ANY hierarchy scheme in this case isn't very good.
