### ISSUE TITLE
Incompatible with the pint 0.20

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-toolkit#1443]
**Describe the bug**
The pint has upgraded to 0.20 which breaks the current openff toolkit

**To Reproduce**
Run 
```python
from openff.units.units import DEFAULT_UNIT_REGISTRY, Measurement, Quantity, Unit
```

**Output**
Will give

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 1
----> 1 from openff.units.units import DEFAULT_UNIT_REGISTRY, Measurement, Quantity, Unit

File ~/miniconda3_x86/envs/test/lib/python3.8/site-packages/openff/units/__init__.py:4
      1 from pint import UnitRegistry
      3 from openff.units._version import get_versions  # type: ignore
----> 4 from openff.units.units import DEFAULT_UNIT_REGISTRY, Measurement, Quantity, Unit
      6 __all__ = [
      7     "unit",
      8     "Quantity",
      9     "Measurement",
     10     "Unit",
     11 ]
     13 unit: UnitRegistry = DEFAULT_UNIT_REGISTRY

File ~/miniconda3_x86/envs/test/lib/python3.8/site-packages/openff/units/units.py:11
      9 import pint
     10 from openff.utilities import requires_package
---> 11 from pint.measurement import _Measurement
     12 from pint.quantity import _Quantity
     13 from pint.unit import _Unit

ModuleNotFoundError: No module named 'pint.measurement'
```
**Computing environment (please complete the following information):**
 - Operating system OSX
 - Output of running `conda list`

```
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-forcefields        2.0.0              pyh6c4a22f_0    conda-forge
openff-interchange        0.2.2              pyhd8ed1ab_0    conda-forge
openff-interchange-base   0.2.2              pyhd8ed1ab_0    conda-forge
openff-toolkit            0.11.2             pyhd8ed1ab_1    conda-forge
openff-toolkit-base       0.11.2             pyhd8ed1ab_1    conda-forge
openff-units              0.1.8              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.7              pyh1a96a4e_0    conda-forge
openmm                    7.7.0           py38h0498e66_0_khronos    conda-forge
openmmforcefields         0.11.2             pyhd8ed1ab_1    conda-forge
pint                      0.20               pyhd8ed1ab_0    conda-forge
```

**Comment by j-wags** [comment]
Thanks for the quick report, @xiki-tempula! I've reproduced this locally. The immediate fix is probably to downpin the pint dependency in the openff-units package. Then the longer term fix is to update openff-units. I'll close this once the downpinned package is made, and will open a new issue on openff-units to update for the api change.

**Comment by j-wags** [comment]
The immediate problem here should be fixed by the new conda package for openff-units ([0.1.8 build 1](https://github.com/conda-forge/openff-units-feedstock/pull/12)). Please reopen if this remains an issue!

**Comment by bieniekmateusz** [comment]
A side note: pint 0.21 is now released and the same problem resurfaces. The new pint forces the installation of openff-toolkit version 0.11.2 which falsely claims to support it.

**Comment by mattwthompson** [comment]
My mistake - I tested that our units package works with 0.21 both locally and in CI but didn't uptake the packaging to allow the upgrade. Fixing it in the conda package: https://github.com/conda-forge/openff-units-feedstock/issues/14

**Comment by bieniekmateusz** [comment]
No reason really, mamba picked Pint 0.21, which was also cached if that's a factor in resolving the environment. Thank you!

**Comment by j-wags** [comment]
Thanks for the report and the quick action!

**Comment by fhh2626** [comment]
same issue in openff-toolkit-base 0.18.0 (openff-units 0.3.1, pint 0.24.4, Windows 11, conda/Python 3.13)
