### ISSUE TITLE
Update examples/new-cli example to tyk2

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#1445]
The current examples/new-cli example uses RIPK2 with multiple chain breaks and a missing pSer.

We might consider updating the example to use tyk2, and renaming the example to just be `cli`.

**Comment by mattwthompson** [comment]
I'm not sure which example you're referring to - is this one in `examples/` in this repo?

**Comment by j-wags** [comment]
I think this was supposed to hit the Perses issue tracker. Looks like this is captured in https://github.com/choderalab/perses/issues/1120, closing!

**Comment by ijpulidos** [comment]
Oh totally, we were trying to find this last dev sync! Woops!
