### ISSUE TITLE
openff-toolkit 0.11 breaks support for interconverting molecule substructures between toolkits

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#1457]
**Describe the bug**
In updating [`perses`](http://github.com/choderalab/perses) to use `openff-0.11`, the implementation of https://github.com/openforcefield/openff-toolkit/pull/1236 removes support for converting incomplete molecules between toolkits. As a result, our atom mapping code---which attempted to use the `Molecule` representation as a unified representation in transforming between toolkits---breaks, since we use a heavy atom scaffold fragment in atom matching. 

The original bug report I made in #1075 highlighted a case where use of the wrong flag in RDKit wrapper caused the identity of the molecule to change when converting heavy-atom scaffolds between toolkits. 

Instead of modifying the default value of the [`hydrogens_are_explicit` flag](https://github.com/openforcefield/openff-toolkit/pull/1236/files#diff-8585a1861f42fa329c6be7e423b55014e0a9de24ecc41f8e6bca24807ac946a0R1605) to address the round-trip molecule corruption, the PR to address the issue appears to have eliminated any support for molecular substructures in toolkit conversions, even though `Molecule` can support molecule substructures. Instead, a `RadicalsNotSupportedError` is thrown, and there is no way to force the toolkit converters to handle conversion for molecule substructures. 

**Proposed solution**

It is _useful_ to have the toolkits validate molecules, but this technically only needs to be done before parameterizing them. Since `Molecule` and the toolkits both support substructures, it doesn't seem to make sense to force an exception to be raised when they are perfectly capable of representing molecules and round-tripping them between toolkits in their existing form---it just requires [setting the `hydrogens_are_explicit=True` flag in the `from_rdkit` initializer](https://github.com/openforcefield/openff-toolkit/blob/b3bcc885ba318f39d771aa7f58504ece3ab4fe31/openff/toolkit/topology/molecule.py#L5076) by default, as #1075 originally suggested. We could move validation to as late as possible---just before the molecule is parameterized in the toolkit.

I might be missing some additional important context that provides rationale for why we need to raise an exception on _conversion_ and not on _parameterization_, but I was not able to find this context in reviewing the threads.

**To Reproduce**
```
>>> from openff.toolkit.topology import Molecule
>>> offmol = Molecule.from_smiles('[c]1[c][c]c([c][c]1)[C][C][N]c2[c][c][c]n[c]2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lila/home/chodera/miniconda/lib/python3.9/site-packages/openff/toolkit/topology/molecule.py", line 1767, in from_smiles
    molecule = toolkit_registry.call(
  File "/lila/home/chodera/miniconda/lib/python3.9/site-packages/openff/toolkit/utils/toolkit_registry.py", line 356, in call
    raise e
  File "/lila/home/chodera/miniconda/lib/python3.9/site-packages/openff/toolkit/utils/toolkit_registry.py", line 352, in call
    return method(*args, **kwargs)
  File "/lila/home/chodera/miniconda/lib/python3.9/site-packages/openff/toolkit/utils/rdkit_wrapper.py", line 1007, in from_smiles
    molecule = self.from_rdkit(
  File "/lila/home/chodera/miniconda/lib/python3.9/site-packages/openff/toolkit/utils/rdkit_wrapper.py", line 1729, in from_rdkit
    raise RadicalsNotSupportedError(
openff.toolkit.utils.exceptions.RadicalsNotSupportedError: The OpenFF Toolkit does not currently support parsing molecules with S- and P-block radicals. Found 1 radical electrons on molecule [C]([C]c1[c][c][c][c][c]1)[N]c1[c][c][c]n[c]1.
```
![image](https://user-images.githubusercontent.com/3656088/200486165-cbd3408b-c73d-4135-afb8-3d9e7c333815.png)

**Computing environment (please complete the following information):**
 - Operating system: `osx`
 - Output of running `conda list`:
```
# Name                    Version                   Build  Channel
openff-toolkit            0.11.3             pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.11.3             pyhd8ed1ab_0    conda-forge
```

**Additional context**
cc #1075 #1236

**Comment by j-wags** [comment]
> Since Molecule and the toolkits both support substructures

This is probably the crux of our disagreement - I don't think that the OpenFF Toolkit Molecule was ever supposed to support substructures. Any previous behavior that happened to be working correctly was undefined. That understanding is why I wrote things like ["**Core Concepts** OpenFF Molecule: A graph representation of a molecule containing enough information to unambiguously parametrize it."](https://github.com/openforcefield/openff-toolkit/blame/e1c0c7ddfe8cf45f2da98d8b0c4dcb09b7a2501e/docs/users/concepts.md#L4) in the docs, and why the [class docstring](https://github.com/openforcefield/openff-toolkit/blame/e1c0c7ddfe8cf45f2da98d8b0c4dcb09b7a2501e/openff/toolkit/topology/molecule.py#L785) says "Immutable chemical representation of a molecule, such as a small molecule or biopolymer." (which I interpret to exclude fragments or substructures).

If I judged this as a feature request now, I'd probably decline it, since this would take a bunch more engineering and  expose new edge cases/bad user experiences. It also contradicts the notion (maybe not written) that the OpenFF toolkit is not intended to be a cheminformatics toolkit.

**Comment by mattwthompson** [comment]
+1 for keeping the `Molecule` class focused on a state that's chemically valid enough for parametrization. Roundtripping stuff between these toolkits is hard.

I imagine there's a way to subclass out of `FrozenMolecule` or break down its components and rebuild them alongside the `ToolkitWrapper` methods with slightly different/customizable behavior, but I can't commit to designing or prototyping that sort of thing (as interesting as it would be!)
