### ISSUE TITLE
`packaging =0.21` breaks things

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1487]
https://packaging.pypa.io/en/latest/changelog.html#id1

**Comment by j-wags** [comment]
Ah rats. Just spent a few minutes seeing if there was an easy solution, but I think that the functionality we relied on is really gone. The version pin should hold us for a while, but I think this will ultimately be resolved by removing the use of packaging altogether like #1418. You deserve every ounce of vindication you feel right now @mattwthompson!

**Comment by mattwthompson** [comment]
We've pinned in deployment and testing, but we'll want to get a proper fix out sooner than later. I think `packagin` is a pretty slow-moving project but in principle it's bad to not be compatible with the most recent major version of something

**Comment by mattwthompson** [comment]
This is causing me issues elsewhere so I'm taking this on.

The "old" behavior of `packaging.version.parse` seems to just spit back the input string without modifications:

```python3
>>> from packaging import __version__, version
>>> __version__
'21.0'
>>> str(version.parse("E.1. .ZXQ"))
'E.1. .ZXQ'
>>> str(version.parse("i am the best basketball player ever"))
'i am the best basketball player ever'
```

whereas now feeding it garbage throws an error

```python3
>>> from packaging import __version__, version
>>> __version__
'23.0'
>>> str(version.parse("i am the best basketball player ever"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/mambaforge/envs/test/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/Users/mattthompson/mambaforge/envs/test/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'i am the best basketball player ever'
>>> str(version.parse("E.1. .ZXQ"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/mambaforge/envs/test/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/Users/mattthompson/mambaforge/envs/test/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'E.1. .ZXQ'
```

so whatever magic we thought was happening by feeding identifiers through this function either didn't do anything or didn't do anything on the cases we tested.
