### ISSUE TITLE
Switch to using QCElemental or Pint for units

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#151]
This would offer nicer serialization support. However, we are tied to OpenMM for system construction for the time being, so we would need interconversion functions between whatever we use internally and simtk units.

**Comment by j-wags** [comment]
This is an unfortunate choice to get stuck with, but, short of rewriting much of our unit-handling code (and then converting them to simtk *anyway* units during system creation), there is no way to do this.

**Comment by j-wags** [comment]
I know that these packages can all _write_ unit-bearing quantities to string, but can they _read_(initialize) from string? I hadn't found the `simtk.unit` functionality for that, but I could check again.

Currently `simtk.unit.Quantity`s are serialized as a list of tuples ( eg. [(unit1, exponent1), (unit2, exponent2)...]), and then the units are `getattr`'d when deserializing. Not pretty, but I was having trouble finding a cleaner way.
Serliazation code: https://github.com/openforcefield/openforcefield/blob/topology/openforcefield/utils/utils.py#L126

**Comment by j-wags** [comment]
That said, I do agree that identical string representations from different packages would help a lot. Like you say, it would let us come back and implement a different unit package later without changing our serialized representations.

**Comment by andrrizzi** [comment]
Not sure it helps, but I wrote a small (and safe) parser for arbitrary mathematical expression to basically solve this problem. Me and @Lnaden used it in YANK to turn an arbitrary strings into a `Quantity` object. The code is now here: [mathematical expression parser](https://github.com/choderalab/openmmtools/blob/master/openmmtools/utils.py#L182-L325) and [quantity_from_string function](https://github.com/choderalab/openmmtools/blob/master/openmmtools/utils.py#L182-L325) (which makes use of the parser).

**Comment by jchodera** [comment]
I was just going to point out @andrrizzi's solution to this problem.

**Comment by j-wags** [comment]
Important note from Slack: https://openforcefieldgroup.slack.com/archives/C8NE3J96U/p1547593277259300

John Chodera [15:01]
In my mind, if we standardize on `pint`, we're just looking for a way to easily get the data into OpenMM when creating a system.
Here's the simplest thing to do right now:
`pint` can define unit systems: https://pint.readthedocs.io/en/0.7.2/systems.html

OpenMM has a natural unit system: http://docs.openmm.org/latest/userguide/library.html#units
(It's defined in code a little more clearly)
We can define a unit system that matches OpenMM's within pint.
Then we just need a function that takes every unit-bearing quantity, checks the dimensions are as expected, and converts it into the OpenMM unit system, stripping units.
Something like
```get_quantity_in_openmm_unit_system(quantity, dimensions)```
Where `dimensions` is the pint dimensions we want to validate against.
That allows us to do strict dimension compatibility checking and convert into a format we can stuff into OpenMM.
And dodge writing a wrapper or large converter.
Without even using `simtk.unit`

**Comment by j-wags** [comment]
For future reference, Simon had a problem where simtk Quantities whose units are reduced to dimensionless are just converted into floats, which was breaking parts of his code where he'd sometimes have unitless Quantities come through and try to ask about their units. Pint doesn't seem like it would have this problem.

```
from simtk import unit
print((8.0*unit.angstrom / unit.angstrom) - 5)


import pint
ureg = pint.UnitRegistry()
print((8*ureg.angstrom / ureg.angstrom) - 5)
print((8*ureg.angstrom / ureg.angstrom) < 5)
```
> 3
> 3.0 dimensionless
> False

**Comment by jchodera** [comment]
cc: https://github.com/pandegroup/openmm/issues/2247

**Comment by mattwthompson** [comment]
#1142 moves to using `openff-units`, which is based on Pint.
