### ISSUE TITLE
Distorted sulfonamide structure after parametrisation and minimisation

### ISSUE THREAD

**Issue by msuruzhon** [openforcefield/openff-toolkit#1522]
**Describe the bug**
When running the following script with an [input sulfonamide](https://github.com/openforcefield/openff-toolkit/files/10520618/data.zip), one obtains a very distorted minimised structure, so this looks like a force field problem. For reference, GAFF2 results in more reasonable geometries for this testcase.

```python
import parmed as pmd
from openff.toolkit.topology import Molecule
from openff.toolkit.topology import Topology
from openff.toolkit.typing.engines.smirnoff import ForceField
from openmm import LangevinIntegrator
from openmm.app import Simulation

# Parametrise
sdf_file_path = "sulfonamide.sdf"
molecule = Molecule.from_file(sdf_file_path)
topology = Topology.from_molecules(molecule)
forcefield = ForceField("openff-2.0.0.offxml")
openmm_system = forcefield.create_openmm_system(topology)
(pmd_system_old,) = pmd.load_file(sdf_file_path)

# Minimise
simulation = Simulation(
    pmd_system_old.topology,
    openmm_system,
    LangevinIntegrator(0, 1, 0.001),
)
simulation.context.setPositions(pmd_system_old.positions)
simulation.minimizeEnergy()

# Output minimised structure
pmd_system_new = pmd.openmm.load_topology(
    topology.to_openmm(),
    openmm_system,
    xyz=simulation.context.getState(getPositions=True).getPositions(),
)
pmd_system_new.save("sulfonamide_minimised.pdb", overwrite=True)
```

<img width="563" alt="image" src="https://user-images.githubusercontent.com/36005076/215130271-ccfdcfd7-80ec-4477-87f4-b2f0eebf2d76.png">

**Computing environment (please complete the following information):**
 - Operating system - macOS Ventura
 - Output of running `conda list`: [env.txt](https://github.com/openforcefield/openff-toolkit/files/10520694/env.txt)

**Additional context**
This seems to be a very specific problem which I haven't seen for many other types of sulfonamides but maybe it can provide some insight into what's going wrong with the current force field version.

**Comment by mattwthompson** [comment]
Thanks for the reproduction - it works great. I'm also seeing a strange conformer when running in through what should be an [identical code path](https://gist.github.com/mattwthompson/d13e47f6d0484c35b5b086975648b16b):

![image](https://user-images.githubusercontent.com/7935382/215144349-7234d95e-f8b6-4a47-81d0-c0776ab5d3e2.png)

I also saw similar behavior starting from a SMILES string instead of your input file and also using or not using OpenEye as the backend.

**Comment by davidlmobley** [comment]
This is odd/interesting -- it may be a FF problem, though we DO have a rather large number of sulfonamides around and I'm quite confident that we do not have an overall problem with sulfonamides in general. So ... hopefully one of our FF folks can check what's up here.

**Comment by msuruzhon** [comment]
Thanks everyone for the replies, `1.3.1` does seem to do the job for this one. I am looking forward to the new instalment of OpenFF!

**Comment by j-wags** [comment]
Good catch - I've opened https://github.com/openforcefield/openff-forcefields/issues/64 on our forcefields repo to discuss this case.
