### ISSUE TITLE
"-pl" option in assign_partial_charges()

### ISSUE THREAD

**Issue by jaketanderson** [openforcefield/openff-toolkit#1533]
**Is your feature request related to a problem? Please describe.**
When using `assign_partial_charges("am1bcc")` on a `Molecule`, `AmberToolsToolkitWrapper` calls on `antechamber` to do am1-bcc calcs. But since antechamber's path length `-pl` is set to the default of `-1` with no way to change it, the calculations are very slow for large molecules like cyclodextrins.

**Describe the solution you'd like**
An exposure of antechamber's `-pl` flag as an optional argument in `openff.toolkit.utils.AmberToolsToolkitWrapper.assign_partial_charges()`.

Here is the current list of arguments accepted:
https://github.com/openforcefield/openff-toolkit/blob/b23992d3dcb9b82631c3f49e3421c930e3e766be/openff/toolkit/utils/ambertools_wrapper.py#L83-L91

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mattwthompson** [comment]
Only have a bit of time, but I can at least suggest offer a few breadcrumbs of workarounds

* `charge_from_molecules` allows for using whatever external tools you wish and bringing in those charges directly
* if you have an OpenEye license, I'm pretty sure that's quicker at generating AM1-BCC charges
* You probably already know that AM1-BCC is not meant to work with large molecules - GCNN methods (https://github.com/choderalab/espaloma/issues / https://github.com/openforcefield/openff-nagl) are appealing workarounds that don't scale horribly with molecule size

**Comment by j-wags** [comment]
Totally agree with @mattwthompson here - We have to limit our surface area with external tools to keep from getting overwhelmed by maintenance costs. The best course of action here is to calculate the charges externally and then use the `Molecule.partial_charges` property and the `charge_from_molecules` keyword argument to `create_openmm_system` to handle molecules that fail by default. (though the other two options Matt mentions would work as well! Espaloma even has the [espaloma_charge](https://github.com/choderalab/espaloma_charge) tool, which is made to do charge assignment with the OpenFF toolkit)
