### ISSUE TITLE
ModuleNotFoundError: No module named 'simtk.openmm.app.element'

### ISSUE THREAD

**Issue by xy127** [openforcefield/openff-toolkit#1546]
Hello,
I am creating a protein-ligand system using modeller of openmm (version 8.0) by the following code:

```
#!/home/ubuntu/miniconda3/bin/python

import sys, time
try:
    from openforcefield.topology import Molecule
except:
    from openff.toolkit.topology import Molecule
from openmmforcefields.generators import SystemGenerator
from simtk import unit, openmm
from simtk.openmm import app, Platform, LangevinIntegrator
from simtk.openmm.app import PDBFile, Simulation, DCDReporter, Modeller, PDBReporter
#from dcdreporter import DCDReporter
from parmed.openmm import StateDataReporter, NetCDFReporter
from rdkit import Chem
import pytraj as pt
import parmed

# read the ligand and add Hs
rdkitmol = Chem.MolFromMolFile('ligand.sdf')
rdkitmolh = Chem.AddHs(rdkitmol, addCoords=True)
ligand = Molecule(rdkitmolh)

# read the protein
protein = PDBFile('protein.pdb')

# Use Modeller to combine the protein and ligand into a complex
modeller = Modeller(protein.topology, protein.positions)
modeller.add(ligand.to_topology().to_openmm(), ligand.conformers[0])
```

An error message occurs at the last line of command:
File "/home/ubuntu/simulation/test.py", line 30, in <module>
modeller.add(ligand.to_topology().to_openmm(), ligand.conformers[0])
File "/home/ubuntu/miniconda3/lib/python3.9/site-packages/openff/toolkit/topology/topology.py", line 2075, in to_openmm
from simtk.openmm.app.element import Element as OMMElement
ModuleNotFoundError: No module named 'simtk.openmm.app.element'

It seems to me that it is a version issue.  I used conda install -c conda-forge openff-toolkit to install packages.  The version is 0.12.0

Thanks.

**Comment by mattwthompson** [comment]
Could you share the output of `conda list` ?

**Comment by xy127** [comment]
![image](https://user-images.githubusercontent.com/68721729/217975741-0ed80c56-e344-443b-829e-0f85f8e1f5f9.png)
![image](https://user-images.githubusercontent.com/68721729/217975854-c5256ea1-73d8-468e-97e8-99d94c475bf6.png)
![image](https://user-images.githubusercontent.com/68721729/217975977-d3c7f704-bfc3-4715-b83e-ab0b1a775dc7.png)
![image](https://user-images.githubusercontent.com/68721729/217976074-9463fdd8-f3f5-4778-90d5-5e15e9168ff0.png)
![image](https://user-images.githubusercontent.com/68721729/217976158-9d143101-4803-440a-a636-c15c7e1ebd13.png)

**Comment by mattwthompson** [comment]
Thanks for the report; this is very surprising, that code was removed before version 0.12.0.

```console
$ git checkout 0.12.0
HEAD is now at 4541d472 Finalize 0.12.0 release notes (#1503)
$ grep -r OMMElement openff/toolkit
```
(outputs nothing)

Is it possible you're running the script from another environment, accidentally? What is the output of these commands?
* `which python`
* `python -c "from openff.toolkit import __file__, __version__; print(__file__, __versio
n__)"`

**Comment by xy127** [comment]
I executed the script in the same environment (omm2)
which python
![image](https://user-images.githubusercontent.com/68721729/217977449-9ba40353-7be2-4194-86b3-a5c77687d912.png)
python -c "from openff.toolkit import __file__, __version__; print(__file__, __versio n__)"
![image](https://user-images.githubusercontent.com/68721729/217977532-2491db31-eddb-4723-8f38-de8f8bf5b49b.png)

**Comment by xy127** [comment]
![image](https://user-images.githubusercontent.com/68721729/217977717-da0ce936-6c99-48ae-8f2d-85cb51d91aaf.png)

**Comment by mattwthompson** [comment]
Thanks for fixing my typo!

It looks like - despite your PS2 suggesting the opposite - your conda environment isn't activated. I notice the path to your `python` executable does not include `omm2` in the path, so you're using the Python interpreter in your base environment. (That environment has version 0.9.0 in it, which is old and doesn't work with OpenMM 8, causing the error you ran into originally). I understand this is confusing - I am frustrated by it often. Usually closing and re-opening your shell, and then re-activating your `omm2` environment, should fix this.

On my machine, see what happens when I call `which python` from my base environment and one of my development environments (named `qcsubmit-test-basic`); notice how the name of the environment shows up in the path of the Python executable and also the toolkit's `__file__`:


```console
$ which python
/Users/mattthompson/mambaforge/bin/python
$ conda activate qcsubmit-test-basic
$ which python
/Users/mattthompson/mambaforge/envs/qcsubmit-test-basic/bin/python
$ python -c "from openff.toolkit import __file__, __version__; print(__file__, __version__)"
/Users/mattthompson/mambaforge/envs/qcsubmit-test-basic/lib/python3.9/site-packages/openff/toolkit/__init__.py 0.12.0
```

I'm using Mambaforge but it's just a drop-in replacement for Miniconda. The environment variable `$CONDA_PREFIX` also usually stores this information, if you ever want to double-check what environment is actually activated.

**Comment by j-wags** [comment]
One suggestion here - There are a million ways that conda configurations can get mixed up, and one really good way to solve them in a terminal session:

`. /home/ubuntu/miniconda3/etc/profile.d/conda.sh`

Then try the `conda activate omm2` again and see if it works.

**Comment by mattwthompson** [comment]
This seems to be a `conda` issue so I'm going to close it for now. If you're still seeing issues - particularly if something like this pops up in a fresh environment - please reopen this and we'll help you sort it out.
