### ISSUE TITLE
Dev chat access

### ISSUE THREAD

**Issue by orionarcher** [openforcefield/openff-toolkit#1549]
I am developing a package that has openff-toolkit as a dependency. There are some features that might be better to contribute into openff-toolkit rather than writing externally. Would it be possible to get added to the dev chat slack to discuss? The link on the GitHub badge has expired.

**Comment by j-wags** [comment]
Sure! We'd love to have you on the project Slack. Could you email me at jeffrey.wagner@openforcefield.org with the email you'd like invited?
