### ISSUE TITLE
Missing methods like `Molecule.from_polymer_pdb()` and `Topology.set_positions`

### ISSUE THREAD

**Issue by nathanmlim** [openforcefield/openff-toolkit#1550]
I've been trying to run the example notebook found here: https://github.com/openforcefield/openff-toolkit/blob/main/examples/toolkit_showcase/toolkit_showcase.ipynb

Aside from changing the import lines to
```
from openff.toolkit.topology import Molecule, Topology
from openff.toolkit.typing.engines.smirnoff import ForceField
```

When I get to the cell which calls `Molecule.from_polymer_pdb("receptor.pdb")`  

I get the error
```
AttributeError: type object 'Molecule' has no attribute 'from_polymer_pdb'
```

Likewise when I get to `top.set_positions(from_openmm(fixer.positions))` 
I get the error
```
AttributeError: 'Topology' object has no attribute 'set_positions'
```

Attached is my conda env
[conda_env.txt](https://github.com/openforcefield/openff-toolkit/files/10758452/conda_env.txt)

**Comment by j-wags** [comment]
The versions in there all look good. Are you sure that your terminal is configured correctly to use conda? Try opening a new terminal, running `. /path/to/conda/etc/profile.d/conda.sh", activating your environment, and running again.

**Comment by mattwthompson** [comment]
It looks like you have a different environment activated in this VS Code window, these methods are found in older versions. I find VS Code sometimes changes the interpreter path without it being obvious to the user.

```python3
>>> from openff.toolkit import Molecule, __version__
>>> __version__
'0.12.0'
>>> Molecule.compute_partial_charges_am1bcc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Molecule' has no attribute 'compute_partial_charges_am1bcc'
```

What's `openff.toolkit.__version__` from these cells? Other variables like `CONDA_PREFIX` might also hint at which environment you're in.
