### ISSUE TITLE
Release on PyPI?

### ISSUE THREAD

**Issue by orionarcher** [openforcefield/openff-toolkit#1552]
**Is your feature request related to a problem? Please describe.**
I would like to use packaging tools like `pip-tools` to handle dependency versioning for a package I am developing. Because `openff-toolkit` is not on PyPI, these tools do not work properly.

**Describe the solution you'd like**
It'd be great to have openff-toolkit on PyPI so it is compatible with `pip-tools`. 

I'm sure there are good reasons this hasn't been done before. Why has OpenFF elected not to upload to PyPI in the past?

**Comment by mattwthompson** [comment]
This is possible but a few moving pieces need to be lined up to pull it off. I'm not sure where it stands as an organizational priority; I think most of our users are content enough with conda these days. We'd also need to ship _all_ of our projects on PyPI. Alone this is not a big deal but it opens up some potential issues in being responsible for i.e. Poetry not solving dependencies well and users still using `python setup.py install`.

The toolkit is pure Python and doesn't take more than a few seconds to build. It should be a pretty lightweight wheel without optimization and probably even smaller with some strategic trimming. Historically the key blockers have been our dependencies (OpenMM, AmberTools, RDKit come to mind). Some of these are available on PyPI now, others are on their way, and I'm probably forgetting a few others as I haven't looked into this for a few months.

OpenMM also used to be a hard dependency where now it could be argued to be optional, though we've worked for so long with this assumption that we'd want to add an `OpenMM=false` row in our CI to safeguard against surprises. Now that `openmm.System` creation is handled by Interchange, it's easier for me to make the case that `Molecule.from_smiles("O")` shouldn't require a full CUDA toolkit installation. I just haven't make a push to implement the change.
