### ISSUE TITLE
Allow setting `Molecule.name` in constructor and some methods

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1566]
**Is your feature request related to a problem? Please describe.**

`Molecule.name` is not relevant in all use cases but critical in some, i.e. exporting to GROMACS and LAMMPS files. When constructing a `Topology` or collection of `Molecule`s that need names, it's a bit clunky.

```python3
from openff.toolkit import Molecule

ligand = Molecule.from_smiles(SMILES)
ligand.name = "LIG"
```

or when dealing with multiple molecules
```python3
topology = Topology.from_molecules(
    molecules=[Molecule.from_smiles(smiles) for smiles in ["C", "CC", "CO"]]
)

for index, name in enumerate(["MET", "ETH", "ETO"]):
    topology.molecule(index).name = name
```

I also found that `Molecule.__init__` allows anything to be passed into its constructor, but only keyword arguments go nowhere and only certain named arguments can be processed:

```python
class FrozenMolecule(Serializable):
    def __init__(
        self,
        other=None,
        file_format: Optional[str] = None,
        toolkit_registry: TKR = GLOBAL_TOOLKIT_REGISTRY,
        allow_undefined_stereo: bool = False,
    ):
        ...

class Molecule(FrozenMolecule):
    def __init__(self, *args, **kwargs):
        super(Molecule, self).__init__(*args, **kwargs)
```

As a result, this trick doesn't work:

```python
>>> Molecule(name='test').name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.10/site-packages/openff/toolkit/topology/molecule.py", line 5150, in __init__
    super(Molecule, self).__init__(*args, **kwargs)
TypeError: FrozenMolecule.__init__() got an unexpected keyword argument 'name'
```

**Describe the solution you'd like**

It's be nice to do this in one pass, i.e.

```python3
ligand = Molecule.from_smiles(SMILES, name="LIG")

topology = Topology.from_molecules(
    molecules=[
        Molecule.from_smiles(smiles, name=name)
        for smiles, name in zip(["C", "CC", "CO"], ["MET", "ETH", "ETO"])
    ]
)
```

Would a patch that adds `name` as a named argument to `Molecule.__init__` be accepted? It would default to the current value of an empty string. This could also be wired to some `Molecule.from_X` methods without breaking existing behavior, I think.

**Additional context**

Related #1028 for a more specific use case

**Comment by j-wags** [comment]
Good catch. Yes, I'd happily accept a patch to fix this!
