### ISSUE TITLE
Py3.7 travis builds downgrade to python 3.6.7 to satisfy OE dependency

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#157]
https://travis-ci.org/openforcefield/openforcefield/jobs/475624199#L1024

@dgasmith suggests that this can be avoided using conda-env, which will compute/resolve dependencies ahead of time.

**Comment by jchodera** [comment]
We should also ask OpenEye what the ETA for a py37 package for `openeye-toolkits` is.

**Comment by j-wags** [comment]
For now, we should re-evaluate the travis/build configuration so these tests fail with 3.7 (that way they'll correctly represent the state of our package in 3.7)

**Comment by dgasmith** [comment]
Aconda-env would fail instead of passing silently. Pulling from pip here is a good idea as OE toolkits may be less dependant on Python version that conda thinks.

**Comment by j-wags** [comment]
To reference the slack conversation -- @davidlmobley asked OE about when `openeye-toolkits` would be available on 3.7, and they recommended getting it from pip.

>Matt Geballe at OE has brought it up with the toolkit maintainers.
> > So I’ve opened a case about this and we hopefully can get this fixed in the next TK release. In talking to the TK team, they mentioned that we didn’t have official support for py37 in October as we didn’t have Windows py37 builds.

> His basic suggestion is that we use pip for all the python versions until we get to the next toolkit release so we can install all from conda.

**Comment by andrrizzi** [comment]
To keep this up-to-date, I've switched to installing OE with pip in #212 to get the Travis tests to pass.

**Comment by jchodera** [comment]
This should be resolved imminently as the py37 release candidates for the OpenEye toolkit were posted a week ago:
https://anaconda.org/OpenEye/OpenEye-toolkits/files
