### ISSUE TITLE
Add `Topology.visualize`

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1604]
**Is your feature request related to a problem? Please describe.**

Most (all?) `Topology`s can be exported to PDB files or one of the many models that `nglview` supports.

**Describe the solution you'd like**

Implement `Topology.visualize` mirroring `Molecule.visualize`.

**Describe alternatives you've considered**

This is clunky:

```
# Visualize
packed_topology.to_file("packed.pdb")
nglview.show_file("packed.pdb")
```

Implementing `Topology.visualize` would also enable optimizations such as skipping the disk I/O.

**Additional context**

Word on the street is that @Yoshanuikabundi has an implementation of this somewhere.

**Comment by j-wags** [comment]
Good idea - I'd accept a PR for this, but not until after the annual meeting. 

Mayhaps you're thinking of https://gist.github.com/Yoshanuikabundi/66007cb9966b1455a259baaf7cd7e7c3#file-utils-py-L443-L464

**Comment by Yoshanuikabundi** [comment]
Yeah I think I might have an even fancier version in the BespokeFit workshop... I'll open a PR after the meeting (dibs).

**Comment by mattwthompson** [comment]
Okay, I'll resolve to not work on this
