### ISSUE TITLE
How to get canonical order transformation

### ISSUE THREAD

**Issue by peastman** [openforcefield/openff-toolkit#1638]
I call `canonical_order_atoms()` on a Molecule.  It returns a new Molecule with atoms in a different order, but I also have other information that needs to be kept consistent with the ordering.  In my current case that's a list of forces on the atoms, but it could also be other things like partial charges or atom types.  How can I determine exactly how the atoms got reordered, so that I can reorder the outside information to keep it consistent?

**Comment by j-wags** [comment]
You should be able to do this by storing an atom map in `offmol.properties['atom_map']`, and then checking this after the canonical reordering. For per-atom information, metadata can hitch a ride through the reordering in the `atom.metadata` dict:

```python
from openff.toolkit import Molecule, RDKitToolkitWrapper
mol = Molecule.from_smiles('CCO')

mol.atom(2).metadata['foo'] = 'bar'
mol.properties["atom_map"] = {i:i for i in range(mol.n_atoms)}
print("symbols before: ", [a.symbol for a in mol.atoms])
rdktkw = RDKitToolkitWrapper()
mol_canon = rdktkw.canonical_order_atoms(mol)
print("symbols after: ", [a.symbol for a in mol_canon.atoms])
print("atom_map after: ", mol_canon.properties["atom_map"])
print("metadata after: ", [a.metadata for a in mol_canon.atoms])

```

> symbols before:  ['C', 'C', 'O', 'H', 'H', 'H', 'H', 'H', 'H']
> symbols after:  ['O', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H']
> atom_map after:  {1: 0, 2: 1, 0: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 3: 8}
> metadata after:  [{'foo': 'bar'}, {}, {}, {}, {}, {}, {}, {}, {}]

The atom map ends up in the form `{new_idx: old_idx}`

I did notice that this only works if I force the use of the RDKit backend - The OE backend loses metadata (I'll raise a new issue for this)

**Comment by peastman** [comment]
Thanks!
