### ISSUE TITLE
can't install openff-tolkit using conda

### ISSUE THREAD

**Issue by paumarc** [openforcefield/openff-toolkit#1735]
**Describe the bug**

I have been trying to install openff-tolkit using conda and it takes a long time, and it nevers finsih

**To Reproduce**
conda install  -c conda-forge openff-toolkit

**Additional context**
i am using an ubuntu os

**Comment by lilyminium** [comment]
Hi @paumarc, could you please try [installing with mamba](https://docs.openforcefield.org/en/latest/install.html)? The mamba solver is much faster than conda and may fix your issue.

**Comment by mattwthompson** [comment]
@paumarc have you been able to install the toolkit? Are there any other issues you've run into?

**Comment by paumarc** [comment]
@mattwthompson yes, everything was fine with mamba
