### ISSUE TITLE
Custom virtual sites

### ISSUE THREAD

**Issue by selimsami** [openforcefield/openff-toolkit#1759]
Hi,

Is there a way to add custom virtual sites, just like you add custom forces? If not, could you point out which parts of the code I would need to change to add my custom virtual site? 

To give you an example, I would like the virtual site placement to depend on the r_ij bond vector times the deviation from the equilibrium bond lengths (r_ij-r0) on top of the common virtual site placement rules like weighted center of geometry. 

(sounds a little crazy, I know)

Thanks.
Selim

**Comment by mattwthompson** [comment]
I was just gonna suggest you try to implement this in OpenMM instead of OpenFF/SMIRNOFF world but I see we're already thinking on the same wavelength!

**Comment by selimsami** [comment]
Haha yes, sorry. I was in the openMM github and I don't know I ended up here... It's one of those days...

**Comment by mattwthompson** [comment]
No problem! The names are similar, after all ...
