### ISSUE TITLE
`type` and `typing.Type` are both used in type annotations. 

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-toolkit#1790]
We should pick one, probably `type`, and stick to it everywhere. In fact, it would probably be worthwhile having a general policy of "If something in `typing` gets replaced by a builtin, use the builtin". So `dict` instead of `typing.Dict` etc.

Based on discussion: https://github.com/openforcefield/openff-toolkit/pull/1782#discussion_r1426730261

Partially addressed by #1782

**Comment by mattwthompson** [comment]
Most - at least common stuff like `Dict`, maybe not `Type` - is captured by `pyupgrade --py39-plus` which does PEP 585 things (Python 3.9+)

* https://github.com/asottile/pyupgrade?tab=readme-ov-file#pep-585-typing-rewrites
* https://peps.python.org/pep-0585/
