### ISSUE TITLE
Allow passing the `-ek` flag to Antechamber (passing custom SQM keywords)

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/openff-toolkit#1800]
**Is your feature request related to a problem? Please describe.**

This is related to our work digging down into some of the issues related to: https://github.com/orgs/openforcefield/discussions/34
It has become increasingly clear to us that at least a portion of the reproducibility issues faced are down to unstable SQM options being passed by antechamber by default.

Antechamber has a `-ek` flag for these circumstances which allows users to manually specify the SQM options desired.

The proposal here is to add an option to feed an optional string for this `-ek` flag.

Currently we are validating things for https://github.com/orgs/openforcefield/discussions/34 using a custom branch with that feature, but we are limited by not having an OpenFF release with it. E.g. we won't be able to run full benchmark checks over alchemiscale.

**Describe the solution you'd like**

Optionally allow passing the `-ek` flag as a user supplied string.

**Describe alternatives you've considered**

1. Fixing this upstream would be ideal, but we are too data poor to make a proper recommendation for now.
2. We could implement our own wrappers around antechamber, althought avoiding duplication of effort would be preferred.

**Additional context**

https://github.com/orgs/openforcefield/discussions/34

**Comment by j-wags** [comment]
I appreciate your help on studying this broader issue and would be open to a temporary private API point to help debug. I'll discuss implementation specifics in #1801.

**Comment by IAlibay** [comment]
To update here - from a short discussion today with @j-wags we have agreed that given things are a bit too uncertain in the short term (at least current investigations towards https://github.com/orgs/openforcefield/discussions/34 are a best inconsistent) it is best to not try to move ahead with this right now.

Short term we will instead go ahead with creating a custom ToolkitWrapper with the necessary changes.

**Comment by j-wags** [comment]
Yes, I agree with @IAlibay's summary. I'll close this issue now but we can reopen if it comes up again in the future.
