### ISSUE TITLE
Add an API point to get a list of available charge methods

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-toolkit#1830]
**Is your feature request related to a problem? Please describe.**

Investigating the available charge methods often requires knowledge of how each toolkit wrapper is implemented, or inspecting the documentation.

**Describe the solution you'd like**

It would be neat to have an API point like `Molecule.get_available_charge_methods(toolkit_registry=GLOBAL_TOOLKIT_REGISTRY) -> list[str]` to get a list of possible values of the `Molecule.assign_partial_charges(partial_charge_method)` argument. This could return a list of all the charges that can be provided by the given toolkit registry, with toolkits that take higher precedence having their charge methods returned first.

**Comment by mattwthompson** [comment]
0.16.0+ 

```python
In [1]: from openff.toolkit import GLOBAL_TOOLKIT_REGISTRY, Molecule

In [2]: Molecule.from_smiles("O").get_available_charge_methods()
Out[2]:
['gasteiger',
 'formal_charge',
 'mmff94',
 'am1-mulliken',
 'am1bccnosymspt',
 'am1bccelf10',
 'zeros',
 'am1bcc',
 'am1elf10']

In [3]: [
   ...:     (wrapper, wrapper.supported_charge_methods)
   ...:     for wrapper in GLOBAL_TOOLKIT_REGISTRY.registered_toolkits
   ...: ]
Out[3]:
[(ToolkitWrapper around OpenEye Toolkit version 2023.2.3,
  ['am1bcc',
   'am1-mulliken',
   'gasteiger',
   'mmff94',
   'am1bccnosymspt',
   'am1elf10',
   'am1bccelf10']),
 (ToolkitWrapper around The RDKit version 2023.09.5, ['mmff94', 'gasteiger']),
 (ToolkitWrapper around AmberTools version 22.0,
  ['am1bcc', 'am1-mulliken', 'gasteiger']),
 (ToolkitWrapper around Built-in Toolkit version None,
  ['zeros', 'formal_charge'])]
