### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1848]
I read through the FAQ and am tagging some sections as slightly or significantly out of date. I don't have the time to work on these now, so I'm noting them for future changes.

* "Can I use an AMBER (or GROMACS) topology/coordinate file as a starting point for applying a SMIRNOFF force field?"
  * This is no longer entirely impossible
* "What about starting from a PDB file?"
  * Missing discussion of recent capabilities of loading some PDB files
  * Possibly reading ligands from (some) PDB files would be enabled by https://github.com/openforcefield/openff-toolkit/issues/1828
* Add section on confusing UX of https://github.com/openforcefield/openff-toolkit/issues/1741
* Add section on "Can I use an Amber force field with SMIRNOFF?"

**Comment by Yoshanuikabundi** [comment]
I've taken a stab at answering these in openforcefield/openff-docs#63 - I'm not sure I addressed the concerns you intended in your first and last dot points so if you'd like to take a look please do! The relevant changes are in [this commit](https://github.com/openforcefield/openff-docs/pull/63/commits/b7b7190b1fd6ca5d22fa89ae8808e9a1cb3f3840)

**Comment by j-wags** [comment]
Presumed closed by https://github.com/openforcefield/openff-docs/pull/63, feel free to reopen if not!
