### ISSUE TITLE
openff.toolkit.topology.Molecule.from_openeye would add atoms to the molecule where it shouldn't

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-toolkit#1860]
**Describe the bug**
I have an OpenEye molecule and I wish to convert this into an OpenFF molecule. I would expect the conversion should keep the number of atoms constant but the conversion add two addition hydrogens to the molecule.

**To Reproduce**

```
from openeye import oechem
from openff.toolkit.topology import Molecule as OpenFFMol
ifs = oechem.oemolistream("test.pdb")
(oemol,) = [oechem.OEMol(mol) for mol in ifs.GetOEMols()]
print(f"The OpenEye molecule has {len(list(oemol.GetAtoms()))} atoms.")
openffmol = OpenFFMol.from_openeye(oemol)
print(f"The OpenFF molecule has {len(openffmol.atoms)} atoms.")
```
[test.pdb.zip](https://github.com/openforcefield/openff-toolkit/files/14959339/test.pdb.zip)

**Output**

```
The OpenEye molecule has 8 atoms.
The OpenFF molecule has 10 atoms.
```

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list`
[conda.env.zip](https://github.com/openforcefield/openff-toolkit/files/14959379/conda.env.zip)

**Comment by j-wags** [comment]
The problem here is that OpenEye is reading the molecule and defining it as having single bonds in the ring, formal charges of 0, and two implicit hydrogens:

```python
from openeye import oechem
ifs = oechem.oemolistream("test.pdb")
(oemol,) = [oechem.OEMol(mol) for mol in ifs.GetOEMols()]
print("formal charges", [atom.GetFormalCharge() for atom in oemol.GetAtoms()])
print("implicit Hs", [atom.GetImplicitHCount() for atom in oemol.GetAtoms()])
print("bond orders", [bond.GetOrder() for bond in oemol.GetBonds()])
```

> formal charges [0, 0, 0, 0, 0, 0, 0, 0]
> implicit Hs [0, 0, 1, 1, 0, 0, 0, 0] <-- This is where the problem is
> bond orders [1, 1, 1, 2, 1, 1, 1, 1]

I think it's possible to tell OpenEye to guess the PDB chemistry differently by disallowing it from adding implicit hydrogens. You can double check that this is the right way to do it with OE support, but adding the `ifs.SetFlavor` line to your code appears to give the outcome you're looking for:

```python
from openeye import oechem
from openff.toolkit.topology import Molecule as OpenFFMol
ifs = oechem.oemolistream("test.pdb")
ifs.SetFlavor(oechem.OEFormat_PDB, oechem.OEIFlavor_PDB_DEFAULT ^ oechem.OEIFlavor_PDB_ImplicitH)
(oemol,) = [oechem.OEMol(mol) for mol in ifs.GetOEMols()]
print(f"The OpenEye molecule has {len(list(oemol.GetAtoms()))} atoms.")
openffmol = OpenFFMol.from_openeye(oemol)
print(f"The OpenFF molecule has {len(openffmol.atoms)} atoms.")
```

> The OpenEye molecule has 8 atoms.
> The OpenFF molecule has 8 atoms.

```python
print("formal charges", [atom.GetFormalCharge() for atom in oemol.GetAtoms()])
print("implicit Hs", [atom.GetImplicitHCount() for atom in oemol.GetAtoms()])
print("bond orders", [bond.GetOrder() for bond in oemol.GetBonds()])
```
> formal charges [0, 0, -1, -1, 0, 0, 0, 0]
> implicit Hs [0, 0, 0, 0, 0, 0, 0, 0]
> bond orders [1, 1, 1, 2, 1, 1, 1, 1]

Please let me know if this resolves your issue.

**Comment by xiki-tempula** [comment]
This is amazing. Thank you.
