### ISSUE TITLE
Difficulty Integrating openff-toolkit Dependency with Poetry/Rye

### ISSUE THREAD

**Issue by nmaeder** [openforcefield/openff-toolkit#1869]
Description
I'm encountering challenges while attempting to integrate the openff-toolkit as a dependency in a package managed by Poetry/Rye. While they natively supports pip, adding the openff-toolkit as a Git repository dependency technically works but fails to install its dependencies, such as openff-toolkit-base.

Request:
It would greatly benefit the community if there were a distribution of the openff-toolkit available on PyPI, inclusive of its dependencies, facilitating seamless integration with tools like Poetry.

Workaround Considerations:
One potential workaround involves manually adding all dependencies of the openff-toolkit to my package. However, this approach introduces unnecessary complexity and bloat, which I aim to avoid. Alternatively, installing the openff-toolkit via Conda and housing my Poetry package within the same Conda environment is possible, but I prefer independence from Conda.

Additional Notes:
If this issue has been addressed elsewhere or if there are existing discussions on this topic, kindly direct me to them.

**Comment by mattwthompson** [comment]
I think this comment still captures the most recent status of distributing OpenFF tools on PyPI: https://github.com/openforcefield/openff-toolkit/issues/1552#issuecomment-1433830048

**Comment by nmaeder** [comment]
Thanks for the quick response and sorry for not searching thoroughly enough! Closing this.
