### ISSUE TITLE
to_inchi() returns empty string on failure

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-toolkit#1897]
**Describe the bug**

`"[H:5][S:3]#[N+:2][S:1][H:4]"` is a molecule that cannot be turned into an InChI due to what looks like an internal software error in the inchi code itself. However, the toolkit returns an empty string upon this failure instead of raising an error, which can be problematic when mass-converting a bunch of molecules while being unaware that this can happen.

**To Reproduce**

```python
from openff.toolkit import Molecule
from openff.toolkit.utils import OpenEyeToolkitWrapper, RDKitToolkitWrapper

Molecule.from_mapped_smiles("[H:5][S:3]#[N+:2][S:1][H:4]").to_inchi(toolkit_registry=OpenEyeToolkitWrapper())
Molecule.from_mapped_smiles("[H:5][S:3]#[N+:2][S:1][H:4]").to_inchi(toolkit_registry=RDKitToolkitWrapper())
```

**Output**

Both toolkits yield warnings along the lines of `Warning: No description(-9995)`, but the OpenFF toolkit still returns an empty string. Could we please raise an error if there's an empty string, just to really warn the user?

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list`

**Additional context**

**Comment by mattwthompson** [comment]
> Could we please raise an error if there's an empty string, just to really warn the user?

I've done this in #1898 - do we care about the same thing for InChi keys as well?

**Comment by lilyminium** [comment]
Thanks for the quick fix @mattwthompson!!

I haven't checked the behaviour of inchi key but as a user I'd like to see an error there as well for similar reasons.
