### ISSUE TITLE
Bad error message when `antechamber` executable not found

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1915]
I don't have the time to fix this now, but it stands out and should be noted. This error message is misleading/wrong:

https://github.com/openforcefield/openff-toolkit/blob/1feb83d484b5f3f885007f76f8ff34d93fb42d91/openff/toolkit/utils/ambertools_wrapper.py#L194-L199

as there is no `charge_mol` in the toolkit. A minimal fix would be updating the error message, a nicer one would mock the executable as missing.

**Comment by j-wags** [comment]
Thanks, happy to take a PR for this. I think just updating the message is sufficient.
