### ISSUE TITLE
`Topology.add_molecule` returns 1-indexed indices, toolkit elsewhere uses 0-index

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1922]
**Describe the bug**

`Topology.add_molecule` returns an index, implied to be the index of the returned molecule. This value is 1-indexed, which is IMHO not in line with user expectations of the toolkit and Python ecosystem broadly. This quirk is [not documented](https://docs.openforcefield.org/projects/toolkit/en/stable/api/generated/openff.toolkit.topology.Topology.html#openff.toolkit.topology.Topology.add_molecule) and I suspect completely accidental. I don't believe anybody actually uses this behavior, but if it's there it should be correct (or documented as a quirk).

The cause is ultimately [here](https://github.com/openforcefield/openff-toolkit/blob/0.16.2/openff/toolkit/topology/topology.py#L2399-L2401) - the 0-index of the last molecule in a topology is the number of molecules _minus one_ - all code paths I checked ended up here by one means or another.

**To Reproduce**

```python
>>> from openff.toolkit import *
>>> topology = Topology()
>>> added_molecule_index = topology.add_molecule(Molecule.from_smiles("O"))
>>> topology.molecule(added_molecule_index)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/topology/topology.py", line 717, in molecule
    return self._molecules[index]
IndexError: list index out of range
>>> added_molecule_index
1
```

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list`: recent environment, using 0.16.2

**Comment by j-wags** [comment]
That's not desired, and it looks like [nobody meaningfully uses this returned index](https://github.com/search?q=%2F%3D+%5B_a-zA-Z0-9%5D%2B%5B.%5Dadd_molecule%2F+AND+openff&type=code) in their code. So we should be good to fix this without delay.
