### ISSUE TITLE
`AtomMappingWarning` is issued too frequently

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-toolkit#1932]
`AtomMappingWarning` is issued by `from_smiles` whenever a mapping is supplied that covers every atom, suggesting the user use `from_mapped_smiles`. This warning should only be issued when `from_mapped_smiles` actually can load the SMILES - ie, when the mappings start at 1 and have no gaps.

```py
>>> smiles = "[H:1][O:4][H:2]"
>>> Molecule.from_smiles(smiles)
AtomMappingWarning: Warning! Fully mapped SMILES pattern passed to `from_smiles`. The atom map is stored as a property in `Molecule._properties`, but these indices are NOT used to determine atom ordering. To use these indices for atom ordering, use `Molecule.from_mapped_smiles`.
>>> Molecule.from_mapped_smiles(smiles)
RemapIndexError: All indices in a mapping_dict for a molecule with 3 atoms must be integers between 0 and 2
```

**Comment by mattwthompson** [comment]
I'm kinda okay with this as demonstrated here - I interpret the warning to be more like "there's a full atom map" and less "we're sure that the atom map makes sense."

I don't see the problem with this behavior - given a fully-mapped SMILES with a bad atom map, 
1. I'm warned that I might want to use `from_mapped_smiles`
2. If I don't care about the mapping, I proceed with my HOH water and the complexity of the atom mapping is bypassed
3. If I do care about the mapping, I ask the toolkit to load it, and then I'm informed that it's gibberish

**Comment by Yoshanuikabundi** [comment]
I guess the issue is that it adds warning pollution for users who use mappings for something other than atom ordering - I was playing with using mappings to map atoms in one molecule to those in another molecule, and when the subsidiary molecule is a subset of the reference molecule the map is full but skips some numbers. In this case, the warning is noise. 

I see that the warning may be useful if someone attempted to create a full mapping but skipped a number or started from zero instead of one or something like that. But in this case, if they're processing multiple mapped SMILES, they only need to get one right to see the warning. And you could just as easily argue that we should warn whenever someone puts any mappings in the SMILES, as maybe they intended to map all the atoms!

I would say once they've seen the warning it becomes noise because now they know that `from_mapped_smiles exists` but I know we've all forgotten that at one point or another :laughing:

**Comment by j-wags** [comment]
I think we should take another angle on this one. 

The suggested change isn't an improvement in all cases. If a user ran `from_smiles` on an input with an unintentionally skipped map value or a fully mapped mol that starts at 0, I'd think they SHOULD get the warning. There's such a large number of possible scenarios in the space of (user intent) x (input deficiencies) that, even if we put a lot of thought into good behavior in all the scenarios we could imagine, we'd still fail to imagine some. There's also a disconnect between @Yoshanuikabundi's use case, where it's an expert user running several inputs in batch mode, versus a first-time user running things interactively on a single input who would change their code in response to an informative warning.

What about options to squelch this warning? Maybe we could provide a context manager that would intercept these warnings, or add something to the FAQ/warning text about filtering warnings if people find this annoying.

**Comment by mattwthompson** [comment]
Since we put the work into making it a highly-specific warning with a message that's unlikely to collide with other warnings, the stdlib already offers users pretty good ways around this in the case that they really want this one (and just this one) ignored. [This classic Ned Batchelder S/O answer](https://stackoverflow.com/a/9134842) could be yoinked into a short FAQ entry, for example.
