### ISSUE TITLE
How to store units and values in SMIRNOFF data?

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#218]
This issue is to collect feedback on how unit-bearing quantities are stored in XML files.

In the 0.1 SMIRNOFF spec, unit-bearing quantities that are attributes of section header elements are stored as `value*unit`. Unit-bearing quantities that are attributes of sub-elements (ie. parameters) have only  `X` defined, while `X_unit` is defined as a separate attribute of the section header.

Example:
```
<vdW potential="Lennard-Jones-12-6" combining_rules="Lorentz-Berthelot" scale12="0.0" scale13="0.0" scale14="0.5" scale15="1" rmin_half_unit="angstroms" epsilon_unit="kilocalories_per_mole" switch_width="1.0*angstrom" cutoff="9.0*angstrom" long_range_dispersion="isotropic">
  <Atom smirks="[#1:1]" epsilon="0.0157" id="n1" rmin_half="0.6000"/>
</vdW>
```

In the 0.2 SMIRNOFF spec, unit-bearing quantities that are attributes of parameter elements are unchanged. However, to be consistent throughout the file, unit-bearing attributes of section header tags have had their `value` and `unit` split. 

Example:
```
<vdW potential="Lennard-Jones-12-6" combining_rules="Lorentz-Berthelot" scale12="0.0" scale13="0.0" scale14="0.5" scale15="1" rmin_half_unit="angstroms" epsilon_unit="kilocalories_per_mole" switch_width="1.0" switch_width_unit="angstrom" cutoff="9.0" cutoff_unit="angstrom" long_range_dispersion="isotropic">
  <Atom smirks="[#1:1]" epsilon="0.0157" id="n1" rmin_half="0.6000"/>
</vdW>
```

Important considerations for future implementations are:
* Avoiding text bloat: If units and values are stored together throughout the file, then there is a substantial overhead added to, for example, bond K values (the string `kilocalorie_per_mole/angstrom**2` would be added ~90 times to the existing SMIRNOFF99Frosst file)
* Being able to preserve precision -- If `1.0` is read in, then it's best if `1.0` is written out (as opposed to `0.9999997`)
* Reducing the likelihood of mistakes/misinterpretation
* That new standards are not specific just to XML, but describe a general data structure.

**Comment by davidlmobley** [comment]
I'm somewhat ambivalent here. I thought we'd decided that 0.2 was better because it removed any ambiguity/reduced potential for error? However, 0.1 does save space.

**Comment by jchodera** [comment]
Perhaps we should shift perspective here: What if we look at this from the perspective of the _object model_ first, and at least focus on refining the API for interacting with the object model first, and then come back to finalize the on-disk representations?

**Comment by mattwthompson** [comment]
With the release of version 0.3 of the SMIRNOFF specification and a few years of its use, I consider this resolved.

If there is a desire to modify it, please re-start this thread in https://github.com/openforcefield/standards/issues
