### ISSUE TITLE
How should we expose keywords and implement logic to handle simulation periodicity and phase?

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#219]
The open force field toolkit will need to handle creation of both periodic and nonperiodic systems. Scientifically, systems can be referred to as "condensed" and "vacuum" (and sometimes "gas") phase. However, there is not a direct correlation from a system being "non-periodic" to it being "vacuum phase", since, for example, implicit solvent simulations are "condensed" but can be "non-periodic".
 
The goal of this PR is to start building toward the toolkit logic and API that will let us unambiguously "do the right thing" scientifically when it comes to system phases and periodicity.

Some important goals that this API should achieve are:
* Have enough granularity to resolve each permutation of inputs to an obviously "right" system setup (or an informative error message)
* Be translatable into a form that could live in the SMIRNOFF spec
* To the greatest extent possible, use scientifically meaningful keywords (eg. "condensed") instead of technical ones (eg. "periodic")
* Somewhat linked to the above, determine what data members Topology should have to ensure that the correct science gets done (eg. maybe Topology should also have a data field to state whether it's vacuum or condensed, in addition to the presence/absence of box vectors)

The objects that will contain inputs(/be part of the API) for this logic are Open Force Field `Topology`s and SMIRNOFF data sources (`ForceField` and `.offxml` files). 

The outputs for this logic are primarily OpenMM `System`s (and all the configuration we can do inside of them). Secondarily, we want to keep in mind how systems will be converted to other formats using ParmEd, InterMol, and other tools.

**Comment by j-wags** [comment]
An example of our current logic to handle this is the following table. It takes the vdW `long_range_dispersion`, the Electrostatics `method`, and whether the input Topology has `box_vectors` set (which we currently interpret as "being periodic"), and yields an `openmm.NonbondedForce`. 

(Note that this method fails because it can't cover implicit solvent, and we probably shouldn't make that assumption about the presence/absence of `box_vectors`)

![Screen Shot 2019-03-29 at 2 51 24 PM](https://user-images.githubusercontent.com/16329175/55264621-40c4ea00-5232-11e9-8eb8-6067581d5f85.png)![Screen Shot 2019-03-29 at 2 52 43 PM](https://user-images.githubusercontent.com/16329175/55264647-563a1400-5232-11e9-9974-56ad78568e31.png)

**Comment by jchodera** [comment]
The biggest question here are: 
1. Do we want SMIRNOFF to describe implicit solvents as well as explicit solvents? 
2. If so, should they be separate force fields, or should one force field describe both implicit and explicit parameters?
3. How do we ensure that the `Topology` object has sufficient information so that force field definitions with explicit solvent parameters can completely parameterize the system, while force field definitions that describe implicit solvents can also completely parameterize the system?
4. How will the force field know when the `Topology` is describing a system that should receive implicit vs explicit solvent parameters?
5. What if we want to support implicit solvents other than water? How and where would we represent this information?

**Comment by davidlmobley** [comment]
> Do we want SMIRNOFF to describe implicit solvents as well as explicit solvents?

Yes

> If so, should they be separate force fields, or should one force field describe both implicit and explicit parameters?

Separate force fields (though acknowledging that initially, someone will create the implicit solvent one by just pulling in parameters directly from the explicit solvent one and adding implicit solvent details). But eventually they will diverge.

>How do we ensure that the Topology object has sufficient information so that force field definitions with explicit solvent parameters can completely parameterize the system, while force field definitions that describe implicit solvents can also completely parameterize the system?

Not quite sure what you mean...? Or, I have no thoughts. 

> How will the force field know when the Topology is describing a system that should receive implicit vs explicit solvent parameters?

Should be different force fields.

> What if we want to support implicit solvents other than water? How and where would we represent this information?

Are there any such models at this point? I don't see how we can support until they exist. 

Perhaps these would be separate force fields in their own right?

**Comment by mattwthompson** [comment]
At this point I feel fairly comfortable closing this; `Topology.box_vectors` handles whether or not the system is intended to be periodic and the SMIRNOFF spec has improved considerably around questions of how non-bonded interactions should be handled with or without periodicity.
