### ISSUE TITLE
Figure out how to hide #doctest:SKIP flags in RTD

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#230]
Example: https://open-forcefield-toolkit.readthedocs.io/en/add-doctests/api/generated/openforcefield.topology.Molecule.html#openforcefield.topology.Molecule.to_file

**Comment by mattwthompson** [comment]
I'm not seeing these in more recent builds

https://docs.openforcefield.org/projects/toolkit/en/stable/api/generated/openff.toolkit.topology.Molecule.html#openff.toolkit.topology.Molecule.to_file
