### ISSUE TITLE
Add contributors whose code was important but didn't make it in

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openff-toolkit#257]
Shuzhe Wang contributed crucial code that helped a great deal with the RDKit implementation, but (at least per GitHub's contributors tracking) none of his actual code made it into our final version of this. We need to acknowledge him somewhere.

I suggest in addition to referring people to the list of GitHub contributors, we provide an explicit list of valuable contributions which are NOT reflected there in our main README.md. This does not need to include people whose contribution is reflected on the automatic list, but should include those who contributed significantly in a way which doesn't show up there.

**Comment by jchodera** [comment]
Agreed! I hadn't realized that his contributions weren't reflected there.

**Comment by mattwthompson** [comment]
In #1673 I've added a bit to the README that covers this. I've only explicitly listed Shuzhe Wang - nobody else immediately came to mind as somebody in a similar situation. This should not be taken to imply others haven't contributed in the same way, and can easily be added by editing this section: https://github.com/openforcefield/openff-toolkit/blob/0b8330302928a2d15492f5f5d502cf64597605a9/README.md#L88-L90
