### ISSUE TITLE
Consider extending Topology as a replacement for OpenMM Topology

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#261]
We might consider extending the OFF [`openforcefield.topology.Topology`](https://open-forcefield-toolkit.readthedocs.io/en/latest/api/generated/openforcefield.topology.Topology.html#openforcefield.topology.Topology) object to be a full-fledged replacement for the OpenMM [`simtk.openmm.app.Topology`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.app.topology.Topology.html#simtk.openmm.app.topology.Topology) object, and try to unify our ecosystem around this object. The [MDTraj `Topology`](http://mdtraj.org/1.9.0/api/generated/mdtraj.Topology.html#mdtraj.Topology) object was a good attempt to go beyond the OpenMM object's limitations, but if we could incorporate the best aspects of both and make ours sufficiently feature-complete, we can likely unify around this object as the new standard.

**Comment by jchodera** [comment]
I also want to point out the [`Molecule`](https://github.com/Acellera/moleculekit/blob/master/moleculekit/molecule.py) object from the @giadefa  [`moleculekit`](https://github.com/Acellera/moleculekit) package as another attempt at the same thing.

We may want to consider harmonizing/standardizing on one kind of object to maximize interoperability.

**Comment by mattwthompson** [comment]
There isn't anything actionable for us to do here; if OpenMM developers do want to standardize around this `Topology` object (I have no opinion) we should coordinate elsewhere.
