### ISSUE TITLE
Ensure parmed export includes atom names

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#302]
Per discussion between @jchodera @slochower @j-wags 

Referencing this notebook: https://github.com/nhenriksen/speakeasy/blob/8a4a057a2797e7b2eb8be0c45724efcfdef2b01b/test/Benzene.ipynb

https://openforcefieldgroup.slack.com/archives/C8NE3J96U/p1557191883036500

David Slochower   [Today at 18:18]
I’m unclear on that. For example, the `prmtop` specification says that atoms should have names. If they don’t have names, maybe things are okay, but technically speaking, it’s out of spec and could lead to unforeseen problems.

4 replies

John Chodera   [41 minutes ago]
Does parmed generate prmtop files without atom names? We can ensure that the Smirnoff toolkit always has atom names defined.

David Slochower   [40 minutes ago]
Yes

John Chodera   [35 minutes ago]
Ok, that should be straightforward to fix!

Can you create an issue "Ensure parmed export includes atom names"? We can easily ensure that unique atom names are defined when the molecules are created or imported, but will need to discuss.

I'm unfortunately heading through an airport right now.

Jeffrey Wagner   [< 1 minute ago]
Right now I think we have atom names as `None` by default. Maybe we could add a function to name them by element and index?

**Comment by slochower** [comment]
Right. This is also a problem if after converting to ParmEd, you try to write a PDB.

**Comment by davidlmobley** [comment]
@j-wags I had in my head that we'd resolved the atom names issue somewhere, but Tran in my group may be running into it... Do you know if htis is resolved?

**Comment by mattwthompson** [comment]
Closing as this code path is no longer encouraged (and might also be fixed by now with the number of changes that have taken place in three years)
