### ISSUE TITLE
Should we support export to FRCMOD via ParmEd?

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#304]
(Initial issue -- Needs cleanup)

Referencing https://github.com/nhenriksen/speakeasy/blob/8a4a057a2797e7b2eb8be0c45724efcfdef2b01b/test/Benzene.ipynb

Per discussion between @slochower @jchodera 

https://openforcefieldgroup.slack.com/archives/C8NE3J96U/p1557191820035200

> John Chodera [18:17]
> Specifically, the problem is going through frcmod and leap, not prmtop directly from parmed (edited) 
> 
> David Slochower [18:18]
> I’m unclear on that. For example, the `prmtop` specification says that atoms should have names. If they don’t have names, maybe things are okay, but technically speaking, it’s out of spec and could lead to unforeseen problems.
> ...
> But certainly the `.frcmod` is not right. 
> 
> John Chodera [18:26]
> The frcmod issue is particularly problematic because of how leap sorts atom type names for assigning impropers (edited) 
> That's something that will need some consideration for how to treat properly.
> It may not be possible to assign more than one improper at a time via leap
> We should definitely open an issue to discuss how frcmod support *should* work, if possible at all

**Comment by j-wags** [comment]
Quick note -- I think the error in that notebook when we attempt to write an FRCMOD:

`ParameterError: Unequal dihedral types defined bewteen C1, C1, C1, and H1`

is caused by having both proper and improper dihedrals for the pattern C-C-C-H

**Comment by slochower** [comment]
> both proper and improper dihedrals defined for the pattern C-C-C-H

Yes! And I'm fairly certain that's because ParmEd doesn't know that one is supposed to be a dihedral and one should be an improper.

**Comment by slochower** [comment]
I think the answer to the title is yes -- otherwise it hurts the claim that this will work fully with AMBER.

**Comment by davidlmobley** [comment]
Just to be clear... what exactly would we be exporting to a frcmod file? Within the larger AMBER ecosystem, a frcmod file COULD encode an entire force field (it is the same format). However... SMIRNOFF force fields are going to be impossible to export (in their entirety) to AMBER force field format (though parameterized systems can be exported to the relevant format for THAT). 

Specifically, frcmod files require atom types, so we can only export things to them which can be encoded by atom types. However, SMIRNOFF force fields don't rely on atom typing and can parameterize systems which cannot be atom typed (such systems exist, e.g. see the GAFF papers). This means that we cannot export our whole force field to frcmod format; it simply is impossible.

Now, what CAN be done is to do what @slochower has done and export the COMPONENTS of the force field which need to be utilized to parameterize a specific system via "system specific" atom types. Specifically, (a) figure out what SMIRNOFF parameters need to get applied to the system, (b) assign every atom in the system a unique atom type, and (c) dump the SMIRNOFF parameters to a frcmod file that would utilize those types.

**Comment by davidlmobley** [comment]
@slochower 
> I think the answer to the title is yes -- otherwise it hurts the claim that this will work fully with AMBER.

What I've always been trying to say is that we would be able to export parameterised systems to `.prmtop` format for use in AMBER. I don't see that it's necessary to export to `.frcmod`.

I agree a tool like your `speakeasy` (basically an `antechamber`-like replacement that gets things ready for leap/tleap) could be useful and could manage prep of SPECIFIC systems with frcmod files; it could let people use the AMBER preparation ecosystem. And this may be a worthy goal. But we should recognize it's not strictly necessary in order for people to be able to simulate SMIRNOFF systems with AMBER.

**Comment by slochower** [comment]
> Specifically, frcmod files require atom types, so we can only export things to them which can be encoded by atom types. However, SMIRNOFF force fields don't rely on atom typing and can parameterize systems which cannot be atom typed (such systems exist, e.g. see the GAFF papers). This means that we cannot export our whole force field to frcmod format; it simply is impossible.

To be clear, since we are talking about _appplying parameters to a specific molecule_ in the limit that every atom in the structure becomes its own atom type, I don't believe there are such limitations. Those are the cases where having a `.frcmod` is useful -- if you want to do any downstream modification or analysis with AmberTools, you will likely need a `.frcmod` at some point (at least, using the workflows that I use). So if I want to simulate a protein with FF14SB and a ligand with SMIRNOFF99Frosst then I need a `.frcmod` for the ligand so that I can use `tleap` to solvate and write a `.prmtop`. There _are_ alternative ways of doing this, like not using `tleap` at all, but I don't think those are tested and wouldn't feel confident recommending them now.

**Comment by davidlmobley** [comment]
> To be clear, since we are talking about appplying parameters to a specific molecule in the limit that every atom in the structure becomes its own atom type, I don't believe there are such limitations.

Agree this is the case, but this issue did not say that was what we were talking about.

> Those are the cases where having a .frcmod is useful -- if you want to do any downstream modification or analysis with AmberTools, you will likely need a .frcmod at some point (at least, using the workflows that I use). 

Agree, yes.

**Comment by davidlmobley** [comment]
No, this should be replaced by Interchange. I have no problem with someone outside implementing something like this if it's important for their workflow, but it's not something we need or should invest in, IMO.

**Comment by mattwthompson** [comment]
Okay, thanks! I only know a bit about what these files are and not much about how they'd actually be used, so I wasn't sure exactly what was being sought here.


If any future Internet explorers arrive at this issue because they want to use FRCMOD files with an Amber + OpenFF workflow, please raise an issue over on the Interchange tracker: https://github.com/openforcefield/openff-interchange/issues
