### ISSUE TITLE
Toolkit Registry Parameter Ordering

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#309]
A very minor and pedantic issue but it would be great if when `toolkit_registry` is present as a function argument, it appears (if possible) at the end of the argument list. For example, I think

```def generate_conformers(self, n_conformers=..., clear_existing=..., toolkit_registry=...):```

is slightly nicer than 

```def generate_conformers(self, toolkit_registry=..., n_conformers=..., clear_existing=...):```

in that often I'll just want to use the default registry, and mainly want to set the other parameters without needed to pass them as `kwargs`.

**Comment by j-wags** [comment]
While I kinda see the merit in this, I don't think it'd be worth the API break at this point.
