### ISSUE TITLE
Improve docstring for Molecule.conformers

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#331]
Indicate shape + dimensionality of `Molecule.conformers` in docstring (it's a list of N_atom x 3 numpy arrays)

**Comment by jchodera** [comment]
Bumping this! The [current docstring](https://open-forcefield-toolkit.readthedocs.io/en/0.5.0/api/generated/openforcefield.topology.Molecule.html#openforcefield.topology.Molecule.conformers) is useless as written.

**Comment by jchodera** [comment]
What units is it even in?

**Comment by j-wags** [comment]
I just checked the docs and this has been fixed some time in the past 18 months.
