### ISSUE TITLE
Get "stable" label building correctly on ReadTheDocs

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#339]
Per https://github.com/openforcefield/openforcefield.org/issues/121#issue-450568033

> RTD is _supposed_ to have [a `stable` branch](https://docs.readthedocs.io/en/stable/versions.html) which corresponds to the latest tagged release, but [that's not building for us](https://open-forcefield-toolkit.readthedocs.io/en/stable/). I'll try to figure out what's up with that and get us a perma-link to an up-to-date SMIRNOFF spec page.

**Comment by Yoshanuikabundi** [comment]
I think I've got this working - your link now points to the 0.9.1 release docs! I just needed to activate the stable version on RTD.

Are there likely to be any links we should point to stable? Maybe some that currently point to latest?

**Comment by j-wags** [comment]
I've confirmed that this works. Thanks @Yoshanuikabundi!
