### ISSUE TITLE
Add information on why we don't support undefined stereochemistry to FAQ

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#352]
This [twitter thread](https://twitter.com/pschmidtke/status/1138950389460557824) suggested we should add a section to our FAQ on why we insist on defined stereochemistry by default.

**Comment by mattwthompson** [comment]
I think this has been added: https://docs.openforcefield.org/projects/toolkit/en/topology-biopolymer-refactor/faq.html#im-getting-stereochemistry-errors-when-loading-a-molecule-from-a-smiles-string
