### ISSUE TITLE
AttributeError: module 'openforcefield'has no attribute 'topology'

### ISSUE THREAD

**Issue by arthuc01** [openforcefield/openff-toolkit#429]
Using VitualBox version of LinuxMint (fresh install). Have installed Anaconda Python. Then followed install instructions .

This does not raise an error
`import openforcefield as off  `

But... 
`from openforcefield.topology import Topology`
gives the error... 
AttributeError: module 'openforcefield'has no attribute 'topology'

```
from simtk.openmm import app
from openforcefield.tests.utils import get_data_file_path, get_packmol_pdb_file_path
pdb_filepath = get_packmol_pdb_file_path('cyclohexane_ethanol_0.4_0.6')
monomer_names = ('cyclohexane', 'ethanol')
```

ModuleNotFoundError: No module names 'openforcefield.test.utils'

**Comment by j-wags** [comment]
@arthuc01 I'm back in the office and can take a look into this. Are you still experiencing the problem? If so, could you paste the output of running `conda list`?

**Comment by davidlmobley** [comment]
Someone I'm working with just ran into a similar error message, and it turned out the problem was that they had an old version of the toolkit. Ensuring the toolkit version was up-to-date ( the conda-forge one) fixed the problem. Marking this as closed.
