### ISSUE TITLE
Avoid problems with converting to AMBER/GROMACS via ParmEd

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openff-toolkit#441]
In https://github.com/openforcefield/openforcefield/issues/440, we've highlighted several bugs which can occur converting a SMIRNOFF system to AMBER/GROMACS format via ParmEd, including:
- incorrect 1-4 scale factors
- missing atom identifiers
- missing residue names

These are not triggered in all circumstances, but seem to be prominent when converting an entirely SMIRNOFF system.

We can fix the residue name and atom identifier issues by ensuring these are populated internally (e.g. https://github.com/openforcefield/openforcefield/issues/440#issuecomment-545192222) ; the 1-4 scale factor issue may take changes on the ParmEd end of things. But at least the issue needs documentation.

**Comment by davidlmobley** [comment]
Perhaps the 1-4 scale factor issue should be split into a separate issue, as this'll be a harder fix i think. Maybe this issue should just involve documenting it/mentioning it in examples, and the separate issue should provide a longer-term fix.

**Comment by j-wags** [comment]
Also linking #303 here since it's thematically related

**Comment by mattwthompson** [comment]
Closing as we're moving away from the ParmEd route.
