### ISSUE TITLE
Drop openeye toolkit failure to load warning unless we're explicitly requesting an openeye toolkit feature?

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#442]
Right now, importing the toolkit without the openeye toolkit being available will issue a surprising warning:
```
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
```
Perhaps we don't want to issue this warning when determining the default set of available toolkits on import?

Instead, only if we're trying to use openeye toolkit-specific features should we issue this warning when we fail?

**Comment by CRingrose94** [comment]
This warning also seems unsuppressible (at least through the usual methods). Adds a lot of unnecessary clutter when calling OpenForceField through an API.

**Comment by jchodera** [comment]
@CRingrose94 : It's a [`logger.warning`](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/utils/toolkits.py#L2917), so presumably could be suppressed by [setting the log level](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel) to [`ERROR` or higher](https://docs.python.org/3/library/logging.html#logging-levels).

**Comment by kbaitsi** [comment]
import logging
logging.getLogger("openff").setLevel(logging.ERROR)

worked for me

**Comment by mattwthompson** [comment]
https://github.com/openforcefield/openff-toolkit/pull/1426
