### ISSUE TITLE
Catching unavailable toolkit exceptions

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#443]
Currently, attempting to use `Molecule.to_iupac()` will generate a [`LicenseError`](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/utils/toolkits.py#L152-L165) if the toolkit is not available. `LicenseError` is a [subclass of `Exception`](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/utils/toolkits.py#L92-L94).

We also have a [`ToolkitUnavailableException`](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/utils/toolkits.py#L102-L105), which is a subclass of `MessageException`.

It would seem that we want a more logical tree structure for exceptions, where maybe there can be special subclasses of `ToolkitUnvailableException`, but fundamentally, if a toolkit isn't available, it should be a `ToolkitUnvailableException` or subclass thereof.

**Comment by mattwthompson** [comment]
This currently throws a `ValueError` since it's fed through the `ToolkitRegistry.call` machinery:

```python3
>>> from openff.toolkit import Molecule
>>> Molecule.from_iupac("asdlkfjdswlkfjdwkfjkdwjfkwj")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/topology/molecule.py", line 3493, in from_iupac
    molecule = toolkit_registry.call(
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/utils/toolkit_registry.py", line 370, in call
    raise ValueError(msg)
ValueError: No registered toolkits can provide the capability "from_iupac" for args "('asdlkfjdswlkfjdwkfjkdwjfkwj',)" and kwargs "{'allow_undefined_stereo': False, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"
Available toolkits are: [ToolkitWrapper around The RDKit version 2022.09.1, ToolkitWrapper around Built-in Toolkit version None]
```
and I'm pretty sure this has always been the case.

The `Molecule` API will only throw a more specific exception if instructed to use a specific registry, i.e.

```python3
>>> Molecule.from_iupac(
...     "blahlbalh",
...     toolkit_registry=ToolkitRegistry(toolkit_precedence=[OpenEyeToolkitWrapper()]),
... )
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/utils/openeye_wrapper.py", line 155, in __init__
    raise ToolkitUnavailableException(
openff.toolkit.utils.exceptions.ToolkitUnavailableException: OpenEye Toolkits are not installed.The OpenEye Toolkits can be installed via `conda install openeye-toolkits -c openeye`
```

but in this case a more specific exception is raised when building up the registry, not while trying to resolve the call:
```python3
>>> toolkit_registry=ToolkitRegistry(toolkit_precedence=[OpenEyeToolkitWrapper()])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/utils/openeye_wrapper.py", line 155, in __init__
    raise ToolkitUnavailableException(
openff.toolkit.utils.exceptions.ToolkitUnavailableException: OpenEye Toolkits are not installed.The OpenEye Toolkits can be installed via `conda install openeye-toolkits -c openeye`
```

In any case, this exception _can_ be caught now with specificity:

```python3
>>> try:
...     Molecule.from_iupac(
...         "bwfjiwjfij",
...         toolkit_registry=ToolkitRegistry(toolkit_precedence=[OpenEyeToolkitWrapper()]),
...     )
... except ToolkitUnavailableException:
...     print('caught this')
...
caught this
```
