### ISSUE TITLE
Document partial charge assignment scheme used by Molecule.compute_partial_charges_am1bcc()

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#447]
Currently, the documentation for [`Molecule.compute_partial_charges_am1bcc()`](https://open-forcefield-toolkit.readthedocs.io/en/0.5.1/api/generated/openforcefield.topology.Molecule.html#openforcefield.topology.Molecule.compute_partial_charges_am1bcc) says almost nothing informative about what is going on under the hood, which is actually quite complex:

* The [canonical AM1-BCC charging method](https://docs.eyesopen.com/toolkits/cookbook/python/modeling/am1-bcc.html) is used to assign ELF10 charges if the OpenEye Toolkit is available.
* Otherwise, RDKit is used to assign a conformation, and [`antechamber -c bcc`](http://ambermd.org/antechamber/) from the [AmberTools]](http://ambermd.org/AmberTools.php) distribution (which uses the `sqm` semiempirical quantum chemical package) is used to assign AM1-BCC charges.

We should also document anything we do to work around issues with OpenEye charging, such as the fallback to standard AM1-BCC and workarounds for the [carboxylic acid issue](https://github.com/oess/openmm_orion/blob/STMD_Analysis/MDOrion/LigPrep/ff_utils.py#L31-L106).

**Comment by mark-cresset** [comment]
Documentation of what happens when sqm fails would also be useful (currently I believe it just raises a generic Exception?)

**Comment by mattwthompson** [comment]
`Molecule.compute_partial_charges_am1bcc` is deprecated and will be removed in 0.12.0 and some other documentation improvements to `Molecule.assign_partial_charges` will land in 0.11.0.
