### ISSUE TITLE
Move Fragmenter into OFFTK

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#463]
**Is your feature request related to a problem? Please describe.**
Much of the functionality in Fragmenter is dependent on the OE toolkit, and it has started being used in situations that don't actually require molecule fragmentation (eg. conformer generation for molecule submission to QCArchive)

**Describe the solution you'd like**
We should migrate basically all of the functionality from Fragmenter into OFFTK. Some parts, like chemi.py, have functionality that could be replaced with ToolkitWrappers.

**Comment by mattwthompson** [comment]
https://github.com/openforcefield/openff-fragmenter is now a (relatively) stable project, is used in a key product, and no longer explicitly depends on OpenEye Toolkits. There hasn't been movement on this so I gather that the current state is acceptable.
