### ISSUE TITLE
Incorrect debug info for improper generation

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#480]
**Describe the bug**
Currently, the debug message emitted by `ForceField.create_openmm_system()` regarding improper torsions is incorrect:
```
INFO     openforcefield.typing.engines.smirnoff.parameters:parameters.py:2247 17 impropers added, each applied in a six-fold trefoil
```
Our current SMIRNOFF spec direct us to add impropers in a `three-fold trefoil`, not a `six-fold trefoil`.

This is just a minor typo.

**Comment by mattwthompson** [comment]
I can't find this anymore - it's either been corrected, removed, or otherwise edited in a way that I can't search for:

```console
$ grep -r "six-fold" openff
openff/toolkit/tests/test_forcefield.py:        # used a six-fold implementation while we now use a three-fold way.
openff/toolkit/tests/test_forcefield.py:        # used a six-fold implementation while we now use a three-fold way.
openff/toolkit/tests/utils.py:    the toolkit, in which the six-fold implementation was changed into
openff/toolkit/tests/utils.py:    # previous to 0.1, where the trefoil improper was six-fold rather
```
These are each comments or docstrings
