### ISSUE TITLE
Molecule.compute_partial_charges_am1bcc() should generate conformers automatically if needed

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#481]
**Is your feature request related to a problem? Please describe.**
Currently, creating a `Molecule` from SMILES and then asking for AM1-BCC partial charges fails with an exception:
```python
>>> molecule = Molecule.from_smiles('CCO')
>>> molecule.compute_partial_charges_am1bcc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda/lib/python3.7/site-packages/openforcefield/topology/molecule.py", line 2014, in compute_partial_charges_am1bcc
    self
  File "/Users/choderaj/miniconda/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 3025, in call
    return method(*args, **kwargs)
  File "/Users/choderaj/miniconda/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 1253, in compute_partial_charges_am1bcc
    "No conformers present in molecule submitted for partial charge calculation. Consider "
Exception: No conformers present in molecule submitted for partial charge calculation. Consider loading the molecule from a file with geometry already present or running molecule.generate_conformers() before calling molecule.compute_partial_charges
```

**Describe the solution you'd like**
Why not just have `molecule.generate_conformers()` called automatically if there are no conformers defined? We could even remove the conformer that is generated afterwards to restore the molecule to its conformer-less state afterwards. There's no need to throw an exception asking the user to do this.

**Describe alternatives you've considered**
Because there is a simple workaround---simply generate conformers---urgency is low.

**Comment by j-wags** [comment]
This has been implemented a long time ago, we just forgot to close the issue. Closing now!
