### ISSUE TITLE
Implement a way to accept outside PRs without exposing OE license

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#549]

**Comment by mattwthompson** [comment]
I assume the OpenEye toolkit relies on the license as a txt file, not decrypted. This is likely a dead end but AZP may be able to store small files in a  "locked down" sort of way: https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops

**Comment by j-wags** [comment]
[Here's an example](https://github.com/cds-snc/covid-alert-server/pull/241#issuecomment-669949157) of how a major organization (the canadian digital service) handled an external PRs whe full CI only runs on branches. Basically, an internal developer took it over and migrated it to a branch, which they carried forward. The downside of this approach is that the external contributor then no longer has access to make subsequent fixes.
