### ISSUE TITLE
Allow to_file to optionally only write the first conformer

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#585]
This is pretty in the weeds, but it would be useful to be able to optionally have `to_file` write out only the first conformer. This is most immediately relevant to PDB files but may also be useful for other formats (right now [only the first conformer](https://github.com/openforcefield/openforcefield/blob/2b48bb7267c7e43db41813a10c37b553ba101474/openforcefield/utils/toolkits.py#L505) of SDF files is written, but that is for other reasons related to #281)

Original comment from Jaime:

I'd say 579 solved a different issue (RDKit not being able to generate multi-model PDBs). What I meant with that comment was that, ideally, we would need an API-level way to tell the toolkit we don't want all conformers written to the PDB, just the first one. Something like this:

```python
self.molecule.to_file(memfile, "pdb", first_model_only=True)
```

or 
```python
self.molecule.to_file(memfile, "pdb", conformers=[0])
# conformers can be None/'all', or a list of indices or slice?
```

_Originally posted by @jaimergp in https://github.com/openforcefield/openforcefield/pull/560_

**Comment by j-wags** [comment]
How about a `write_multiconformer` kwarg instead, which defaults to `False`, but could be `True` or `list[conformer]`? That way, we'd have standard behavior across all of our write formats (with the default suitable for SDF), but some writers could support multiconformer output.

**Comment by mattwthompson** [comment]
That seems sensible (and I think people may prefer adding kwargs over adding explicit args?) - what other formats, if any, should be considered here?

**Comment by mattwthompson** [comment]
This would be implicitly closed if the coming topology refactor modifies the molecule class to only store on conformer per instance.
