### ISSUE TITLE
Improve Documentation of ParameterHandler.add_parameter

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#606]
**Describe the solution you'd like**

The documentation for `ParameterHandler.add_parameter` should more clearly state that the parameter will be added to the end of the parameter list, and also briefly state this means it will be the first to be considered when parameters are being assigned. 

This should then cross-link to the assignment docs (/ SMIRNOFF spec?) which goes into more detail on why this is important.

**Comment by mattwthompson** [comment]
This was updated at some point in time and I believe the docstring now includes the relevant information:

https://docs.openforcefield.org/projects/toolkit/en/stable/api/generated/openff.toolkit.typing.engines.smirnoff.parameters.ParameterHandler.html#openff.toolkit.typing.engines.smirnoff.parameters.ParameterHandler.add_parameter
