### ISSUE TITLE
PPC64LE Conda Install

### ISSUE THREAD

**Issue by DNA2RNA** [openforcefield/openff-toolkit#633]
Hi,

Is there any chance Open Force Field might get a PPC64LE or noarch installation option?

Thanks!

**Comment by mattwthompson** [comment]
We'd like to do one or both of these at some point in the future but, unfortunately, it's probably not something we can do in the short term. The OpenFF toolkit is pure Python, so it comes down tot he dependencies. Most are distributed as noarch and/or ppc64le, but some important ones don't seem to be: RDKit and OpenMM stick out to me at a glance. They can easy probably be compiled locally but I have not tried myself and don't have access to a PowerPC machine at the moment to test.  I'm not sure about the OpenEye toolkits, if you happen to have a license.

**Comment by jchodera** [comment]
(cc @j-wags @jaimergp  @peastman)

We are actively working to migrate OpenMM to `conda-forge`, where we hope to be able to support both ppc64le and ARM packages. Hopefully this can be wrapped up quickly.

We might open an issue on the https://github.com/conda-forge/rdkit-feedstock to see if they could add ppc64le and ARM support as well, and at least find out what the roadblocks are.

**Comment by DNA2RNA** [comment]
Hi Matt and John,

Thank you for the information. I see the RDKit issue you mention. As for OpenMM (and ParmEd), I managed to get them working on a Summit-style cluster with these Conda installations:
```
conda install https://anaconda.org/omnia-dev/openmm/7.4.0/download/linux-ppc64le/openmm-7.4.0-py37_cuda101_0.tar.bz2
conda install -c jchodera parmed
```
It looks like I will be able to pre-parametrize our ligands on an x86 system then move them over to ppc64le systems using the magic of serialization.

As a side note, I'd just like to say that the work you folks are doing is absolutely outstanding :)

Thank you all again,
Gabriel

**Comment by jchodera** [comment]
I had built those manually using recipes I created for building on Summit:
https://github.com/inspiremd/conda-recipes-summit

Now that `conda-forge` has a mechanism for building for `ppc64le` and `arm`, however, we're very much hoping to get this working ASAP.

**Comment by mattwthompson** [comment]
Opened an issue on the RKDit feedstock: https://github.com/conda-forge/rdkit-feedstock/issues/52

**Comment by jaimergp** [comment]
You can track the progress for `ppc64le` and `aarch` CF packages in this PR:
https://github.com/conda-forge/openmm-feedstock/pull/23

Note these are not released, so you would need to run `conda build recipe` on that repo on Summit to manually compile it yourself.

There are some issues with the CPU platform on `ppc64le` if it's compiled with GCC 8.x, but GCC 7.x works fine. Other platforms are not affected.

**Comment by jaimergp** [comment]
Updates on this:

* OpenMM 7.5 will work ok with ppc64le - see https://github.com/conda-forge/openmm-feedstock/pull/23
* RDKit is now being distributed for ppc64le on conda-forge - see https://github.com/conda-forge/rdkit-feedstock/pull/54
* AmberTools too - see https://github.com/conda-forge/ambertools-feedstock/pull/16

Having OpenMM on conda-forge is still ongoing, but we will get there. Is any other critical dependency I am missing?

**Comment by mattwthompson** [comment]
This is now a bit stale - this _probably_ works now given the improvements to upstream packaging, but it still might not.

If this is still desired and it does not work, please re-open.
