### ISSUE TITLE
Iterating over nodes not guaranteed to produce consistent ordering

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#723]
We're working to track down the bug in https://github.com/choderalab/qmlify/issues/6 that leads to irreproducibility when attempting to reproduce the plots in the Jupyter notebook. It appears that running from the pickled data leads others to reproduce data that is inconsistent with the data produced with the original notebook, even though this is consistently reproduced on the same machine that generated the pickled files.

The issue is potentially caused by [this code](https://github.com/openforcefield/Arsenic/blob/master/arsenic/stats.py#L156-L158) to enumerate the nodes of a `nx.Graph` (or `DiGraph`) in a particular order that is then used to order the absolute free energies. However, NetworkX graphs are more like a `dict` than a `list`, and enumerating nodes from a NetworkX graph is not guaranteed to report the nodes in the same order each time. This may cause the order to differ when the pickle is loaded on another machine (with perhaps a different version of NetworkX installed)>

Instead, if we need to render the nodes in a consistent order each time, we should use an [Ordered Graph](https://networkx.github.io/documentation/stable/reference/classes/ordered.html), or a different approach to ensuring we pick a consistent ordering.

**Comment by hannahbrucemacdonald** [comment]
I think you put this on the wrong issue tracker @jchodera
