### ISSUE TITLE
VdW Cutoff Ignored when Electrostatic Handler Present

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#734]
**Describe the bug**
The non-bonded cutoff is hardcoded in several places (the [`vdWHandler`](https://github.com/openforcefield/openforcefield/blob/7091de5daf03abfa487e7c3619eafcfcbff91d1d/openforcefield/typing/engines/smirnoff/parameters.py#L3226) and the [`ElectrostaticsHandler`](https://github.com/openforcefield/openforcefield/blob/7091de5daf03abfa487e7c3619eafcfcbff91d1d/openforcefield/typing/engines/smirnoff/parameters.py#L3524)). This hardcoded value overwrites the value set by both the `vdWHandler` and the `ElectrostaticsHandler`.

**To Reproduce**

```
# Create a dummy topology containing only argon and give it a set of
# box vectors.
topology = Molecule.from_smiles("[Ar]").to_topology()
topology.box_vectors = numpy.eye(3) * unit.nanometers

# Create the FF
force_field = ForceField()

# Add only a VdW handler.
vdw_handler = vdWHandler(version=0.3)
vdw_handler.method = "cutoff"
vdw_handler.cutoff = 6.0 * unit.angstrom
vdw_handler.scale14 = 1.0

vdw_handler.add_parameter(
    {
        "smirks": "[#18:1]",
        "epsilon": 1.0 * unit.kilojoules_per_mole,
        "sigma": 1.0 * unit.angstrom
    }
)

force_field.register_parameter_handler(vdw_handler)

# Map the FF to the dummy topology
system = force_field.create_openmm_system(topology)

assert numpy.isclose(
    system.getForce(0).getCutoffDistance().value_in_unit(unit.angstrom),
    6.0
)

# Add an electrostatics handler.
electrostatics_handler = ElectrostaticsHandler(version=0.3)
electrostatics_handler.cutoff = 6.0 * unit.angstrom
electrostatics_handler.method = "PME"
force_field.register_parameter_handler(electrostatics_handler)

library_charges = LibraryChargeHandler(version=0.3)
library_charges.add_parameter(
    {
        "smirks": "[#18:1]",
        "charge1": 0.0 * unit.elementary_charge,
    }
)
force_field.register_parameter_handler(library_charges)

system = force_field.create_openmm_system(topology)

assert numpy.isclose(
    system.getForce(0).getCutoffDistance().value_in_unit(unit.angstrom),
    6.0
)
```

**Output**

```AssertionError``` on the final assert.

**Computing environment (please complete the following information):**
 - `openforcefield = 0.7.2`

**Comment by SimonBoothroyd** [comment]
It seems #917 only partially resolves the issue. If the electrostatics handler and vdW have the same cutoff (but different from 9.0 A) then the fix in #917 won't be applied and the issue will still persist. The hardcoded `ElectrostaticsHandler` cutoff needs to be properly set to resolve this.

See e.g.:

```

print(
    system.getForce(0).getCutoffDistance().value_in_unit(unit.angstrom)
)

>>> 9.0
```

**Comment by SimonBoothroyd** [comment]
(cc @mattwthompson @j-wags )

**Comment by mattwthompson** [comment]
Seems like this line is the culprit: https://github.com/openforcefield/openff-toolkit/blob/a5ed656b84e1999560f4898a87f238a6ddf0aac6/openff/toolkit/typing/engines/smirnoff/parameters.py#L3892
