### ISSUE TITLE
Globally instantiated mutable args

### ISSUE THREAD

**Issue by dgasmith** [openforcefield/openff-toolkit#780]
There are several places in the toolkit such as [here](https://github.com/openforcefield/openforcefield/blob/1eb4e3feeff07d8a3281e3d6889262326b15259f/openforcefield/utils/toolkits.py#L4900) (found by @swails) with mutable args instantiated in the function definition. In these cases the argument is global and appending/extend to this value will expand the mutable value in all instantiations. It looks like there are `if arg is None` statements below which would be correct if it was instantiated as None.

**Comment by mattwthompson** [comment]
Thanks for the catch - could you point to other cases, or how to find them? I can't seem to find other public cases that match the `=[]`/`={}` [pattern](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments)
