### ISSUE TITLE
Allow Smirnoff99Frosst force fields with lower case names 

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-toolkit#815]
**Is your feature request related to a problem? Please describe.**
When trying to run the smirnoff99Frosst forcefields via QCArchive the name is lowered somewhere within the internals of QCFractal/QCEngine which means the force field can not be loaded on Linux but this still works on mac as it ignores the capitalization when loading the file.

**Describe the solution you'd like**
It would be great if the toolkit could even out this behaviour by replacing any lower case names which reach the toolkit with the correct capitalization before loading the file. I think this could be done with the following code placed here https://github.com/openforcefield/openff-toolkit/blob/bb40b067484f968b39092b8a892bbc12f2d6d010/openff/toolkit/typing/engines/smirnoff/forcefield.py#L1087
```python
import re
source = re.sub("frosst", "Frosst", source)
```

**Describe alternatives you've considered**
I have tried changing this in other places in the chain but I think it makes the most sense here as this is the main call to load the forcefield file.

**Comment by mattwthompson** [comment]
Would there be any issues for downstream users if we did case-insensitive matching between the input argument and the files found by searching the entry points? That would be implemented somewhere around [this](https://github.com/openforcefield/openff-toolkit/blob/bb40b067484f968b39092b8a892bbc12f2d6d010/openff/toolkit/typing/engines/smirnoff/forcefield.py#L1099) line
