### ISSUE TITLE
Look for antechamber in $AMBERHOME if not found in $AMBERHOME/bin

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#830]
**Is your feature request related to a problem? Please describe.**
With some Amber installs, `antechamber` isn't properly added to `$PATH`.

**Describe the solution you'd like**
If `antechamber` isn't in the path, check to see if `$AMBERHOME` has been set and search within `${AMBERHOME}/bin`? 

**Describe alternatives you've considered**

**Additional context**
https://github.com/michellab/BioSimSpace/issues/175#issuecomment-775877860
https://github.com/openforcefield/openff-toolkit/blob/de8a4a545351301adfe424dff0d879b2dd13bc0b/openff/toolkit/utils/toolkits.py#L4442
https://github.com/openforcefield/openff-toolkit/blob/de8a4a545351301adfe424dff0d879b2dd13bc0b/openff/toolkit/utils/toolkits.py#L4458-L4461

This will probably be hard to reproduce in CI, since the `AmberTools` package on `conda-forge` puts `antechamber` in `$PATH`. On my machine ` $AMBERHOME` is set to `$CONDA_PREFIX`, which we don't have to remove.

I've never actually built AmberTools myself, so I could be overlooking something more obvious.

**Comment by lohedges** [comment]
In your test script you could monkey-patch `distutils.spawn.find_executable`, i.e. bind it to another function that returns `None`, which is what it returns when it fails to find `antechamber` in the `PATH`.

**Comment by mattwthompson** [comment]
This implementation should also check that the AmberTools version is newer than some minimum version (I think 2020 or newer). I think we have previously enforced this version check only at the packaging level - this is not currently a suitable solution because `openff-toolkit-base` does not enforce this (it could be updated to do so).

Related https://github.com/openforcefield/openff-toolkit/issues/571 and probably other issues

**Comment by lohedges** [comment]
We now enforce our own check within BioSimSpace by running `antechamber -v` and checking that the version in the welcome message is >= 20. (If there is no output, or the output doesn't match the desired format, then we also disable OpenFF support.)

**Comment by mattwthompson** [comment]
This hasn't cropped up as a problem in a couple of years - please re-open if it is.
