### ISSUE TITLE
Use ELF10 for system creation when OpenEyeToolkitWrapper is available

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#837]
**Describe the bug**
Original message by @SimonBoothroyd:

> Am I right in thinking that since the 0.7.0 release of the toolkit we don't actually use ELF10 to compute partial charges, even when OE is installed and licensed?
> (i.e. in #471 the call to a toolkit compute_partial_charges_am1bcc function by a molecules compute_partial_charges_am1bcc function was replaced by a call to assign_partial_charges with am1bcc explicitly stated)

The above is a regression introduced in the 0.7.0 release. We should fix it by having `ToolkitAM1BCCHandler.create_force` do a `try/except` where it attempts to use `partial_charge_method='am1bccelf10'` first, and then, if there's a `ChargeMethodUnavailableError`, drops down to `partial_charge_method='am1bcc'`. This will cause ELF10 to be used (if available), and vanilla AM1-BCC otherwise. 

**Additional context**
cc #447

**Comment by mattwthompson** [comment]
Fixed in 0.10.4 (and 0.11.0+)

 #990 appears to be a duplicate
