### ISSUE TITLE
numpy array cannot be serialized

### ISSUE THREAD

**Issue by yuanqing-wang** [openforcefield/openff-toolkit#843]
**Describe the bug**
When serializing a molecule, if it has a numpy array annotation in its data field, namely partial charges, it cannot be serialized since the numpy array will be converted to a `bytes` rather than a `str`.

https://github.com/openforcefield/openff-toolkit/blob/adde241a052b31a2ffa6356b2c2ded34694270cc/openff/toolkit/utils/utils.py#L672

**To Reproduce**
```
molecule = Molecule.from_smiles('C')
molecule.assign_partial_charges("zeros")
import json
json.dump(
    mol.to_dict(),
    open('mol.json', 'w')
)

```

**Output**
```
TypeError: Object of type bytes is not JSON serializable
```

**Computing environment (please complete the following information):**
 - OS: CentOS
 - Output of running `conda list` 

**Additional context**

**Comment by yuanqing-wang** [comment]
Proposing a solution in #842

**Comment by mattwthompson** [comment]
Hi @yuanqing-wang, thanks for pointing out this confusing behavior.

I see two things at play

1. The `to_dict` methods don't return something safe for JSON serialization. There are separate `to_json` methods that more carefully handle converting things to types that JSON supports. This could probably be documented better - maybe some warnings in the [`docstring`](https://open-forcefield-toolkit.readthedocs.io/en/0.9.0/api/generated/openff.toolkit.topology.Molecule.html#openff.toolkit.topology.Molecule.to_dict).   I can see why it's confusing that `to_dict` converts the arrays to bytes - I _think_ this is to make the other serializers happy. Would something like this handle your use cases?

    In: 
    ```python3
    import json

    from openff.toolkit.topology import Molecule


    mol = Molecule.from_smiles("C")
    mol.assign_partial_charges("zeros")
    json.dump(mol.to_json(), open("mol.json", "w"))

    print(type(mol.to_dict()['partial_charges']))  # <class 'bytes'>
    print(type(json.loads(mol.to_json())['partial_charges']))  # <class 'list'>

    new = Molecule.from_json(json.load(open("mol.json")))
    
    assert new == mol
    ```
    the file:
    ```json
    {"name": "", "atoms": [{"atomic_number": 6, "formal_charge": 0, "is_aromatic": false, "stereochemistry": null, "name": ""}, {"atomic_number": 1, "formal_charge": 0, "is_aromatic": false, "stereochemistry": null, "name": ""}, {"atomic_number": 1, "formal_charge": 0, "is_aromatic": false, "stereochemistry": null, "name": ""}, {"atomic_number": 1, "formal_charge": 0, "is_aromatic": false, "stereochemistry": null, "name": ""}, {"atomic_number": 1, "formal_charge": 0, "is_aromatic": false, "stereochemistry": null, "name": ""}], "virtual_sites": [], "bonds": [{"atom1": 0, "atom2": 1, "bond_order": 1, "is_aromatic": false, "stereochemistry": null, "fractional_bond_order": null}, {"atom1": 0, "atom2": 2, "bond_order": 1, "is_aromatic": false, "stereochemistry": null, "fractional_bond_order": null}, {"atom1": 0, "atom2": 3, "bond_order": 1, "is_aromatic": false, "stereochemistry": null, "fractional_bond_order": null}, {"atom1": 0, "atom2": 4, "bond_order": 1, "is_aromatic": false, "stereochemistry": null, "fractional_bond_order": null}], "properties": {}, "conformers": null, "partial_charges": \"stereochemistry\": null, \"fractional_bond_order\": null}], \"properties\": {}, \"conformers\": null, \"partial_charges\": [0.0, 0.0, 0.0, 0.0, 0.0], \"partial_charges_unit\": \"elementary_charge\"}"
    ```

1. There are several ways of serializing and de-serializing arrays and array-like data (in this case `unit.Quantity`-wrapped arrays) and separate concerns for different places the data could be (in memory, printed to the user, and on disk via different serializers). We end up using bytes for some of the disk serializations thinking that we can safely handle the de-serialization and that it should be compact on disk. The current solution "just works," at least for the behavior we have round-trips written for (dicts in memory, JSON, msgpack, and some others on disk). Are there other use cases we should look to cover?

**Comment by yuanqing-wang** [comment]
Ah ok I see. I simply missed the `to_json` method and used `to_dict` instead. `to_json` would work for me perfectly. Thanks!

**Comment by jchodera** [comment]
If we still have other serialization schemes like to_bson() that use binary formats, that may be more useful to you, @yuanqing-wang
