### ISSUE TITLE
Remove stale tests

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#877]
**Is your feature request related to a problem? Please describe.**
Many thousands of unit tests are skipped, including many that are not skipped for stable reasons. This results in CI logs like
```
1696 passed, 9704 skipped, 4 xfailed, 3 xpassed, 38 warnings in 261.75s (0:04:21) =
```
that make it hard for developers or reviewers to notice when the number of skipped tests changes. A case of this happening is #874, in which I inadvertently  turned off some thousands of tests for several months. Presumably in the development and review process, I and the PR approver did not notice the number of skipped tests ballooning out of control because it was already at such a large number that it was meaningless.

**Describe the solution you'd like**
Tests that are skipped for reasons other than speed or missing optional dependencies are technical debt.  These should be updated ASAP, removed temporarily (i.e. out of the repo or to folders that `pytest` will not collect) or permanently.

**Describe alternatives you've considered**
N/A

**Additional context**
Many tests are skipped for good reasons, like the `--runslow` tests or the `OpenEyeToolkitWrapper` tests on the RDKit-only builds. The most accurate metric would be the number of tests skipped on the nightly builds with each toolkit installed.

Many more tests are skipped because of MiniDrugBank weirdness, which is in the process of being replaced with a better dataset (no tagged issue?)

**Comment by j-wags** [comment]
@mattwthompson points out that has since been completed:

https://github.com/openforcefield/openff-toolkit/actions/runs/5459199413/jobs/9934943686#step:15:563
```
= 23888 passed, 18 skipped, 94 xfailed, 310 xpassed, 16127 warnings in 5059.29s (1:24:19) =
```

**Comment by mattwthompson** [comment]
In #1286 I tucked stuff away into `openff/toolkit/tests/_stale_tests.py`, which should probably get whittled away at over time
