### ISSUE TITLE
RDKit stereo enumeration does not flip existing stereochemistry

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#892]
**Describe the bug**

Attempting to enumerate all stereoisomers of a molecule with already defined stereochemistry yields no stereoisomers when using the RDKit backend.

**To Reproduce**

Using the toolkit:

```
>>> off_molecule = Molecule.from_smiles('[H][C@@](F)(Cl)Br')
>>>
>>> print(len(off_molecule.enumerate_stereoisomers(
>>>     undefined_only=False, toolkit_registry=RDKitToolkitWrapper())))
>>> 
>>> print(len(off_molecule.enumerate_stereoisomers(
>>>     undefined_only=False, toolkit_registry=OpenEyeToolkitWrapper())))

0
1
```

comparison with the RDKit toolkit directly:

```
>>> rdkit_molecule = Chem.MolFromSmiles('[H][C@@](F)(Cl)Br')
>>> options = StereoEnumerationOptions(onlyUnassigned=False)
>>>
>>> for isomer in EnumerateStereoisomers(rdkit_molecule, options=options):
>>>     print(Chem.MolToSmiles(isomer))

F[C@H](Cl)Br
F[C@@H](Cl)Br
```

**Output**
The full error message (may be large, that's fine. Better to paste too much than too little.)

**Computing environment (please complete the following information):**
 - Operating system: OSX
 - Output of running `conda list` :

```
rdkit                     2020.09.3        py38h4648dd3_0    conda-forge
openeye-toolkits          2020.2.0                 py38_0    openeye
openff-toolkit            0.9.1           dev_0    <develop>
```

**Additional context**

**Comment by SimonBoothroyd** [comment]
I did a bit more digging and managed to create a MWE which highlights this issue using only RDKit. If I try to manually sanitize the molecule created by RDKit I only see the original isomer returned:

```
>>> rdmol = Chem.MolFromSmiles("[H][C@@](F)(Cl)Br", sanitize=False)
>>> Chem.SanitizeMol(rdmol)
>>>
>>> options = StereoEnumerationOptions(onlyUnassigned=False)
>>>
>>> for isomer in EnumerateStereoisomers(rdmol, options=options):
>>>    print(Chem.MolToSmiles(isomer))

[H][C@@](F)(Cl)Br
```

whereas if I let RDKit do the santization:

```
>>> rdmol = Chem.MolFromSmiles("[H][C@@](F)(Cl)Br", sanitize=True)
>>> 
>>> options = StereoEnumerationOptions(onlyUnassigned=False)
>>> 
>>> for isomer in EnumerateStereoisomers(rdmol, options=options):
>>>     print(Chem.MolToSmiles(isomer))

F[C@H](Cl)Br
F[C@@H](Cl)Br
```

things behave as expected.

**Comment by SimonBoothroyd** [comment]
Digging into the C++ a bit more to try and see what the differences are between the sanitisation done internally by the `MolFromSmiles` method and the `SanitizeMol` method, it seem like internally the `MolFromSmiles` method also

* calls `RemoveHs` with `implicitOnly = false`, `updateExplicitCount = true` and `sanitize = true` (see [here](https://github.com/rdkit/rdkit/blob/0370b6cc57b279cd25a677b28f766dfe2a05021d/Code/GraphMol/SmilesParse/SmilesParse.cpp#L387-L389) and [here](https://github.com/rdkit/rdkit/blob/0370b6cc57b279cd25a677b28f766dfe2a05021d/Code/GraphMol/SmilesParse/SmilesParse.h#L75-L76))
* followed by a call to `AssignStereochemistry` with `cleanIt = true`, `force = true`, `flagPossible = true`

The toolkit enumeration code currently calls `AssignStereochemistry` as `Chem.AssignStereochemistry(rdmol, force=True, flagPossibleStereoCenters=True)` with `cleanIt = False`. If I update that line to `cleanIt = True` then things seem to behave as expected.

So the main question for @j-wags (and maybe @jthorton) - is there a reason not to set `cleanIt = True`?

**Comment by jthorton** [comment]
@SimonBoothroyd Good catch I think I just missed this on the implementation and I think we should always be using `cleanIt=true`
