### ISSUE TITLE
Creating a ForceField can fail if a child directory is deleted

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#898]
**Describe the bug**

Creating a force field can fail if a child directory of a child of the current working directory is deleted while a force field is [searching for a file with the specified name](https://github.com/openforcefield/openff-toolkit/blob/e54052afcf0ee401fb65d84e995d53f1f77e3240/openff/toolkit/typing/engines/smirnoff/forcefield.py#L1097-L1103) due to `glob` trying to look for the next child in the directory it's currently looking in.

The current behaviour of that function does actually look slightly suspect but for different reasons than those that cause the issue - if I try to create a `ForceField` from `my-force-field.offxml` I expect the code to try and load the path as I've specified it, not to hunt for that file in all possible sub-directories and possibly finding a version of the file which I didn't want to load.

**To Reproduce**

The issue is tricky to reproduce without monkey patching internal functions, but I ran into this issue when I was trying to create a force field from a string representation, and the script that was doing that was based in a directory which contained thousands of child directories which were slowly being deleted.

**Output**

```
  File "/XXX/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 357, in __init__
    self.parse_sources(sources, allow_cosmetic_attributes=allow_cosmetic_attributes)
  File "/XXX/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 901, in parse_sources
    smirnoff_data = self.parse_smirnoff_from_source(source)
  File "/XXX/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1099, in parse_smirnoff_from_source
    for file_path in dir_path.glob("**/*.offxml"):
  File "/XXX/pathlib.py", line 1125, in glob
    for p in selector.select_from(self):
  File "/XXX/pathlib.py", line 578, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/XXX/pathlib.py", line 525, in _select_from
    with scandir(parent_path) as scandir_it:
FileNotFoundError: [Errno 2] No such file or directory: 'a/child/directory'
```

**Computing environment (please complete the following information):**
 - Operating system: OSX
 - Output of running `conda list`: 

```
openff-toolkit            0.9.1              pyhd8ed1ab_1    conda-forge
openff-toolkit-base       0.9.1              pyhd8ed1ab_1    conda-forge
python                    3.9.2           h2502468_0_cpython    conda-forge
```

**Additional context**

**Comment by mattwthompson** [comment]
Should be fixed by #1002 - please re-open if not!
