### ISSUE TITLE
File size issues with parmed-exported AMBER files

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openff-toolkit#90]
Just for the record, I wanted to point out (so I don't lose the info) that SMIRNOFF force fields currently result in very large file sizes when written to AMBER format for systems comprised of large numbers of symmetric molecules. e.g., a box with 1000 cyclohexane molecules can result in a 16 GB AMBER parameter file. 

This is a result of an annoying interplay of how we match OEMols to Topology molecules in order to assign parameters (for symmetric molecules the match differs from molecule to molecule); this leads to multiple instances of the same molecule being recognized as distinct residues/molecules (rather than repeated instances of the same residue/molecule) in ParmEd which results in ridiculously large memory use/file sizes when going to AMBER formats, as further described on the updated density/dielectric benchmark repo https://github.com/kyleabeauchamp/B2/issues/5

This should be fixed by the re-engineering that will take place as we design our Topology object. https://github.com/openforcefield/openforcefield/pull/86

**Comment by davidlmobley** [comment]
@j-wags @andrrizzi have you guys checked that this has been resolved now that we've done the Topology revamp? It should have been, but worth checking.

**Comment by andrrizzi** [comment]
I haven't checked. I've assigned this to the 0.2.2 milestone, but we can close it if @j-wags verified this already.

**Comment by j-wags** [comment]
I haven't verified this. Let's keep it as a future milestone.

**Comment by jchodera** [comment]
Even better, what about creating an explicit test that takes in a water box and checks that each molecule receives the same relative parameter ordering?

**Comment by j-wags** [comment]
I like this idea. As a note: Large systems will take a while to parameterize and could slow down our tests. We should use a system consisting of just a few (<10) waters with different orderings, rather than a large water box. (Issue #253 is open to optimize system creation speed)

**Comment by jchodera** [comment]
Small water boxes sound like a great way to start!

**Comment by davidlmobley** [comment]
That's better than it was before, @andrrizzi ; still far too big, but not "impossibly big" as before.

You may be right. Do you have an idea of what we'd need to do for fake atom types? And what they are used for in the prmtop? (At one point I knew this but it's been far too long.)

**Comment by andrrizzi** [comment]
> but not "impossibly big" as before.

That's correct. Notice however that the example is just T4 Lysozyme in vacuum. When I tried with a cyclohexane box, I found the size of the prmtop file to be ~80MB for 100 cyclohexanes and ~320MB for 200 cyclohexanes so we may get to impossibly big very fast.

> what we'd need to do for fake atom types?

As far as I see it, this would require
1. Parsing the OpenMM `System` and identify particles that are involved in `Nonbonded`/`HarmonicBond`/...`Force`s with the exact same parameters.
2. Modify the `Topology` to pass to `parmed.openmm.load_topology()` to have the `Atom.id` attributes reflecting the atom types.
We can add this to the to-be-implemented `ForceField.create_parmed_structure()` method, or possibly directly in ParmEd, although, on first thought, this seems to be a generally-useful feature that we may want to have implemented in the toolkit independently from ParmEd.

I think it will require a few days of work to implement and test it, but I don't currently expect to find insurmountable problems.

**Comment by jchodera** [comment]
One important question that should guide our approach to a solution is "when do we need to solve this?". Do we need to export systems containing liquids or proteins to Amber prmtop now, or are we just going to be combining small molecules using the parmed + operator for the short term?

If we can wait a bit, rather than hacking some sort of fake atom types into the OFF toolkit, we could do one of 
1. Work to change this behavior in ParmEd by enabling more intelligent type compression
2. Develop a more clever antechamber replacement ("speakeasy")
3. Create a new OFF object model for representing parameterized systems that we can use to generate prmtop files directly, eliminating the need for parmed

I very much favor (3) since we can solve a multitude of issues simultaneously by focusing or mid term efforts there.

**Comment by davidlmobley** [comment]
I agree with @jchodera 's questions, and I also agree the *best* solution would be (3). To me, though a key consideration is what the difference in developer time is. I worry something like (3) would be six months to a year or more for a dedicated developer, whereas (1) or (2) might be a couple of days. If they were equal developer time, or only differed by a factor of 2 or 3 I'd definitely prefer option (3) since it would make us no longer dependent on ParmEd which has an uncertain future. However, my intuition is that "building a ParmEd replacement", while important, is not something within what we can manage with our current fudning.

If we have an estimate of developer time this week we could discuss this in the governing and advisory board calls next week.

**Comment by j-wags** [comment]
> When I tried with a cyclohexane box, I found the size of the prmtop file to be ~80MB for 100 cyclohexanes and ~320MB for 200 cyclohexanes so we may get to impossibly big very fast.

There seems to be N^2 scaling going on here with the number of particles. I suspect that this is a result of pre-computing possible vdW interaction pairs, while assuming that each particle is unique.

 I have a few thoughts:
1) If we want a naming scheme that keeps file size under control, we could assign the vdW parameter IDs (`n1`, `n2`, etc). If the vdW parameter pre-computation issue is really the problem, this should at least bring our file size down to O(N_particles), which isn't ideal, but is at least more contained.
2) If pre-computation also occurs for electrostatic interactions, and the same vdW parameters might get assigned to particles with different electrostatics, then we will have to solve a more difficult problem.
3) AMBER performance may be degraded on our systems when the memory footprint gets this large. I've heard tales of adjacent-memory-lookup magic driving their GPU code speed, and we'll probably lose this if we can't keep our relevant parameters dense.

**Comment by andrrizzi** [comment]
Thank you all for your input.

> when do we need to solve this?

I agree that this may not be the most urgent use case right now and stabilizing the toolkit right now has higher priority.

I also like any of the proposed solutions, although I think that in any of those cases, the problem will still boil down to the implementation of an algorithm that creates fake atom types either in ParmEd, the OFF toolkit, or the OFF ecosystem in general.

**Comment by jchodera** [comment]
> I think that in any of those cases, the problem will still boil down to the implementation of an algorithm that creates fake atom types either in ParmEd, the OFF toolkit, or the OFF ecosystem in general.

If we go with option (3), where we retain the ability to connect parameterized particles to their origin parameter entry, then we won't have to create such an algorithm---we can simply utilize this existing information to compress the table of interactions.

I've elaborated on option (3) in this issue: #310 

If we can punt this to the time when we will need biopolymer parameters converted to SMIRNOFF, we would have enough time to fix this via option (3).

**Comment by mattwthompson** [comment]
I consider this resolved; I wasn't able to find any large Amber files and the toolkit's test suite generally no longer relies on them.

```console
$ find . -type f -name '*.prmtop' -exec ls -lh {} \;
-rw-r--r--  1 mattthompson  staff    11K Sep 23 09:36 ./openff/toolkit/data/systems/monomers/ethanol.prmtop
-rw-r--r--  1 mattthompson  staff    15K Sep 23 09:36 ./openff/toolkit/data/systems/monomers/cyclohexane.prmtop
-rw-r--r--  1 mattthompson  staff   8.2K Sep 23 09:36 ./openff/toolkit/data/systems/monomers/methane.prmtop
-rw-r--r--  1 mattthompson  staff    14K Sep 23 09:36 ./openff/toolkit/data/systems/monomers/butanol.prmtop
-rw-r--r--  1 mattthompson  staff    11K Sep 23 09:36 ./openff/toolkit/data/systems/monomers/propane.prmtop
-rw-r--r--  1 mattthompson  staff   1.0M Sep 23 09:36 ./openff/toolkit/data/systems/amber/cyclohexane_ethanol_0.4_0.6.prmtop
-rw-r--r--  1 mattthompson  staff    11K Jun  8  2022 ./examples/deprecated/testing/test_system_conversion/ethanol.prmtop
-rw-r--r--  1 mattthompson  staff    15K Jun  8  2022 ./examples/deprecated/testing/test_system_conversion/cyclohexane.prmtop
-rw-r--r--  1 mattthompson  staff    21K Jun  8  2022 ./examples/deprecated/testing/test_impropers/1,2-ditert-butylbenzene.prmtop
-rw-r--r--  1 mattthompson  staff    11K Jun  8  2022 ./examples/deprecated/testing/test_impropers/benzene.prmtop
-rw-r--r--  1 mattthompson  staff    14K Jun  8  2022 ./examples/deprecated/testing/test_impropers/o-xylene.prmtop
