### ISSUE TITLE
Have create_openmm_system generate CustomNonbondedForce objects

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#914]
**Is your feature request related to a problem? Please describe.**
OpenMM provides `NonbondedForce` as an way to handle non-bonded forces, both vdW and electrostatics, in the same object. This is great for vanilla setups, i.e. those with cutoff LJ and PME electrostatics. This is, however, not consistent with the design of the SMIRNOFF spec in which vdW and electrostatic forces are generally kept separate. For example, one should be able to design a SMIRNOFF-style force field that has different non-bonded methods or cutoffs for vdW and electrostatics, which gets hard/impossible to store in a single `NonbondedForce`.

**Describe the solution you'd like**
@j-wags recently learned that a single `NonbondedForce` can be split up into several `CustomNonbondedForce` objects with no or minimal performance losses (https://github.com/openforcefield/openff-toolkit/pull/833#issuecomment-821722615). I don't know if **all** instances of `NonbondedForce` should be taken out.

**Describe alternatives you've considered**
This is in general a tangly portion fo the codebase - it's been a daunting task to document, it takes about 100 LOC to encode in the unit tests, and we still run into cases in which a single `NonbondedForce` is incompatible with the SMIRNOFF spec. Things have been working fine for the main use case (our mainline force fields  that use cutoff vdW and PME electrostatics) but I doubt that a single `NonbondedForce` is just not extensible enough long-term - given the option of separate `CustomNonbondedForce`s!

**Additional context**
Some issues that have cropped up: #380 #191 #734 #882 https://github.com/openforcefield/openff-toolkit/issues/219

There might be impacts on downstream developers if people expect to be able to run `.getForces()` and extract data from the single `NonbondedForce` that is found. I would think most users would not be hugely impacted by a change that keeps simulations running similarly to as before.

**Comment by j-wags** [comment]
Thinking about the design of a fix -- if at all possible, I'd advocate supporting the previous behavior as default, and splitting into two `CustomNonbondedForces` as a optional override. This would preserve people's old workflows that relied on getting the `NonbondedForce` from the resulting system. 

So the kwarg could be `forcefield.create_openmm_system(topology, try_to_combine_nonbonded_forces=True`). There would be three possibilities for its behavior:

* If `try_to_combine_nonbonded_forces==True`, then we check whether it's a supported ES + vdW combo and the cutoffs are the same, and if so, we pass a new kwarg `create_custom_nonbonded_force=False` to every `create_force` and `postprocess_system`, which has them provide the old behavior. 

* If `try_to_combine_nonbonded_forces==False` , then we pass `create_custom_nonbonded_force=True` to each `create_force` and `postprocess_system` method, and let them on their merry way. The one wrinkle in this case is that `postprocess_system` will need new logic to fish out the proper `CustomNonbondedForce` from the system -- This will probably take the form of [comparing symbolic representations](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce.getEnergyFunction) of the Forces already present from the earlier `create_force` step. 

* If `try_to_combine_nonbonded_forces==True`, but the settings of the handlers are incompatible, then we emit a warning ("hey, I can't combine those into a single nonbonded force") and pass `create_custom_nonbonded_force=True` to the handlers. 

How does this sound?

**Comment by mattwthompson** [comment]
Implemented here (maybe not 1:1): https://github.com/openforcefield/openff-interchange/pull/201
