### ISSUE TITLE
Generator for 1-4 pairs from a Topology

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#922]
**Is your feature request related to a problem? Please describe.**
To interface with MD engines, I often need to access a list of the 1-4 pairs, defined as atoms separated by a shortest path of precisely 3 bonds

**Describe the solution you'd like**
I would like an API point like `Topology.pairs_14` that is a generator over tuples of atom indices of each 1-4 pair in a topology.

A more general solution might be to have a more general function that returns all pairs separated by a minimum distance, specified as an argument to the function `n`. This should behave identically to `.pairs_14` in the case of `n=3`. There are some force fields that scale 1-3 or 1-5 interactions (and even some [crazy people](https://github.com/openmm/openmm/issues/1926) that try to include 1-2 interactions!) so there would be some utility of making this behavior more general. It may be worth limiting the value of `n` to avoid computational explosions (I can't wrap my head around calling a function like this with i.e. `n` > 10).

I expect this to be feasible to implement with some intelligent looping and/or `networkx` calls. There should be tests that cover basic behavior in small molecules, "gotchas" in rings, and maybe a slow test that tests the performance of a system of a few thousand small molecules.

**Describe alternatives you've considered**
There are some workarounds, like one-off code I've written and [similar functionality](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.NonbondedForce.html#simtk.openmm.openmm.NonbondedForce.createExceptionsFromBonds) in OpenMM. Just iterating over proper torsions (`Topology.propers`) and tracking atoms #1 and #4 does not work because some pairs in rings can be pairs by multiple paths, i.e. two atoms in a 5-membered ring can simultaneously be 1-4 and 1-3 pairs, and in typical MM force fields this would be treated as a 1-3 interaction and completely excluded.

Keeping behavior like this in one place (the toolkit) would help code duplication and buggy behavior resulting from people (like me) doing bad one-off implementations.

**Additional context**

cc @ijpulidos - Please add this to the requirements doc - though I'd expect any solution that can fit into the current API to be portable to the refactor.

**Comment by j-wags** [comment]
I agree with this feature request -- The SMIRNOFF spec also hints at support for custom 1-3 and 1-5 scaling factors, so this will be handy in general. 

The specific spot for this logic would be in the `Molecule` class, with an additional access method in the `Topology`, which simply loops over all the molecules it contains. 

> Please add this to the requirements doc

We can add it to the current Topology refactor wishlist, though it's unrelated to the major theme of the effort, so it would be near the lower end of the priorities. I think it'll be easier to slip this in as a distinct effort (it'll be nice to use this as a morale boost/opportunity for forward progress when we get blocked on complicated polymer implementation issues)

**Comment by mattwthompson** [comment]
Yes - low-priority "requirement" is fair, as it doesn't need to be implemented urgently

**Comment by mattwthompson** [comment]
This should be doable now with `mol.nth_degree_neighbors(n_degrees=3)`, coming in release 0.9.3 or 0.10.0
