### ISSUE TITLE
PSI4 and openff-toolkits compatibility 

### ISSUE THREAD

**Issue by ph7klw76** [openforcefield/openff-toolkit#928]
I started with a fresh environment under miniconda
i installed openff-toolkits 
and then installed PSI4
or vice versa

The 2 modules seem not compatible, It keeps looping in resolving conflicts
I tried in python 3.9 environments, python 3.7 and python 3.8 environments. It is the same.

**Comment by pavankum** [comment]
installing both simultaneously with the following command worked for me, you can give this a try
`conda create -n env_name -c conda-forge -c psi4/label/dev psi4 openff-toolkit`

**Comment by j-wags** [comment]
Thanks for writing in, @ph7klw76.

Could you let us know a bit more about your computing environment? Are you on mac or linux? We've had some difficulties making envs with psi4 and usually use the trick that @pavankum posted.

**Comment by mattwthompson** [comment]
Recent versions of Psi4 (1.8+, maybe earlier) are available on `conda-forge` and should work better together now. Please re-open or file a new issue if there are still issues!
