### ISSUE TITLE
Add ForceField.assign_partial_charges

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#945]
**Is your feature request related to a problem? Please describe.**

Users often want to see which partial charges would be assigned to a `Topology` or `Molecule` by a given `ForceField` object. However, this isn't directly accessible. Instead, users have to run:

```
from openff.toolkit.typing.engines.smirnoff import ForceField
ff = ForceField('openff-1.3.0.offxml')
sys, ret_top = ff.create_openmm_system(mol.to_topology(), return_topology=True)
[*ret_top.reference_molecules][0].partial_charges
```

**Describe the solution you'd like**

We could make a convenience method that just runs the above and returns the partial charges. 

```
class ForceField:
    ...
    def assign_partial_charges(molecule, toolkit_registry=None)
```

We could also modify the existing `Molecule.assign_partial_charges` to accept a `ForceField` as an argument (which would be exclusive with accepting a `partial_charge_method` or `use_conformers` kwarg)

**Describe alternatives you've considered**

The name might be easy to confuse with `Molecule.assign_partial_charges`. I don't know whether this is good or bad. Also, we may think about how we can change the name to keep people from thinking this is a necessary prerequisite to running `create_openmm_system`.

One tricky thing with the above implementation is that it will ALSO run through valence parameter assignment, and if any of those are missing, it will raise an error instead of returning the partial charges. This could by circumvented by knowing _ahead of time_ which handlers can assign partial charges, and only running those. However this conflicts with the current plugin architecture, since a user could define a new charge method and we wouldn't know about it in time to include it in this list.

**Comment by lilyminium** [comment]
> We could make a convenience method that just runs the above and returns the partial charges.

> The name might be easy to confuse with Molecule.assign_partial_charges. I don't know whether this is good or bad. Also, we may think about how we can change the name to keep people from thinking this is a necessary prerequisite to running create_openmm_system.

`get_partial_charges` sounds less stateful?

**Comment by mattwthompson** [comment]
> One tricky thing with the above implementation is that it will ALSO run through valence parameter assignment

I'd be +1 on a solution that only runs through the handlers relevant for partial charge assignment. This would lead to better performance, maintainability, and stability (i.e. no errors raised for missing torsions when a user just wants partial charges). We've discussed this elsewhere #619 and might be satisfied by https://github.com/openforcefield/openff-system/pull/200 (ETA next week).
