### ISSUE TITLE
Topologies cannot be instantiated from other topologies

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#946]
**Describe the bug**

Trying to create a `Topology` from another `Topology` instance yields an excpetion due to a non-existant method

**To Reproduce**
Steps to reproduce the behavior. A minimal reproducing set of python commands is ideal.

If the problem involves a specific molecule or file, please upload that as well.

```
from openff.toolkit.topology import Molecule, Topology
Topology(other=Topology.from_molecules(Molecule.from_smiles("C")))
```

**Output**
The full error message (may be large, that's fine. Better to paste too much than too little.)

```
Traceback (most recent call last):
  File "/XXX/openff-toolkit/scratch/at-am1/run.py", line 160, in <module>
    main()
  File "/XXX/openff-toolkit/scratch/at-am1/run.py", line 110, in main
    Topology(other=Topology.from_molecules(Molecule.from_smiles("C")))
  File "/XXX/openff-toolkit/openff/toolkit/topology/topology.py", line 1321, in __init__
    self.copy_initializer(other)
AttributeError: 'Topology' object has no attribute 'copy_initializer'
```

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list` 

**Additional context**

**Comment by mattwthompson** [comment]
This was fixed some time ago, though I don't recall which PR specifically.

```python
>>> from openff.toolkit import Molecule, Topology
>>> topology = Topology.from_molecules(Molecule.from_smiles("C"))
>>> from openff.units import unit
>>> topology.box_vectors = [4, 4, 4] * unit.nanometer
>>> Topology(topology)
<openff.toolkit.topology.topology.Topology object at 0x10d386d60>
