### ISSUE TITLE
[Request] chemical_environment_matches keyword(unique=False, max_matches=None)

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-toolkit#967]
**Is your feature request related to a problem? Please describe.**

Sometimes I want unique matches without having to sort through the non-unique matches myself.

**Describe the solution you'd like**

It would be easy and convenient to give `chemical_environment_matches` `unique` and `max_matches` keywords to pass to OpenEye or RDKit respectively. `unique=False` and `max_matches=None` would replicate current behaviour, where `max_matches is None` sets it to 0 for OpenEye and the largest possible int in RDKit.

**Describe alternatives you've considered**

**Additional context**

**Comment by lilyminium** [comment]
Generally closed by #1036; max_matches isn't really important for sorting through non-unique matches.

**Comment by j-wags** [comment]
Thanks for running the bookkeeping on this, @lilyminium. I'm super behind on everything as you can tell so I really do appreciate this.
