### ISSUE TITLE
hasattr not supported by _ParameterAttributeHandlers

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-toolkit#986]
**Describe the bug**

`hasattr` on a non-existent attribute of a `_ParameterAttributeHandler` subclass (e.g. LibraryChargeType) breaks in an `IndexError` instead of returning True/False.

**To Reproduce**
Steps to reproduce the behavior. A minimal reproducing set of python commands is ideal.

If the problem involves a specific molecule or file, please upload that as well.

```python
from openff.toolkit.typing.engines.smirnoff import ForceField
ff = ForceField('openff_unconstrained-1.3.0.offxml')
lc = ff.get_parameter_handler("LibraryCharges")
hasattr(lc.parameters[0], "charge2")
```

**Output**
The full error message (may be large, that's fine. Better to paste too much than too little.)

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
openff/toolkit/typing/engines/smirnoff/parameters.py in __getattr__(self, item)
  1170             try:
-> 1171                 return indexed_attr_value[index]
  1172             except IndexError:

openff/toolkit/utils/collections.py in __getitem__(self, item)
   122             return self.__class__(super().__getitem__(item))
--> 123         return super().__getitem__(item)
   124 

IndexError: list index out of range

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
<ipython-input-134-072f04b5c4f0> in <module>
----> 1 hasattr(lc.parameters[0], "charge2")

openff/toolkit/typing/engines/smirnoff/parameters.py in __getattr__(self, item)
  1171                 return indexed_attr_value[index]
  1172             except IndexError:
-> 1173                 raise IndexError(
  1174                     f"'{item}' is out of bound for indexed attribute '{attr_name}'"
  1175                 )

IndexError: 'charge2' is out of bound for indexed attribute 'charge'

```

**Computing environment (please complete the following information):**
- Operating system
- Output of running `conda list` 

**Additional context**

`hasattr` does not have its own dunder method, but rather relies on `getattr` raising an `AttributeError`. The relevant `getattr` method raises, variously, IndexErrors and KeyErrors as well as the AttributeError, so `hasattr` unexpectedly breaks. IMO any error raised in an `__getattr__` should be some version (e.g. a subclass) of `AttributeError` to preserve the functionality of this inbuilt function.

There may be other classes with this issue too, I haven't looked around.

https://github.com/openforcefield/openff-toolkit/blob/b2b76bb457c2a8235f86e887d75ee815030b605e/openff/toolkit/typing/engines/smirnoff/parameters.py#L1152-L1203

**Comment by lilyminium** [comment]
Related: #771

**Comment by j-wags** [comment]
Oh, nice. I just took the time to grok this and it makes sense. Yes, I think you're right that these `IndexError`s and `KeyError`s should be `AttributeError`s. Are there any downsides to this?

**Comment by lilyminium** [comment]
If any users or the code base has worked around it with the following snippets in their code, it'll no longer work:

```python
try:
	getattr(lc.parameters[0], "charge2") # or hasattr(lc.parameters[0], "charge2")
except (KeyError, IndexError):
	# do something for this specific error
```

Making a new error that is both a subclass of `AttributeError` and the existing error takes care of this problem.

e.g. 

```python
class MissingIndexedMappedAttributeError(AttributeError, IndexError, KeyError, OFFTKException):
    ...
```

**Comment by mattwthompson** [comment]
I'd be happy with either solution - `MissingIndexedMappedAttributeError` or simply a hard "break" to make the behavior more in line with how attributes are supposed to work
