### ISSUE TITLE
test_forcefield.py:test_overwrite_bond_orders failure in CI

### ISSUE THREAD

**Issue by adalke** [openforcefield/openff-toolkit#994]
**Describe the bug**

I regularly get the following error during CI:
```
=================================== FAILURES ===================================
_________ TestForceFieldParameterAssignment.test_overwrite_bond_orders _________
openff/toolkit/tests/test_forcefield.py:4243: in test_overwrite_bond_orders
    assert bond1.bond.fractional_bond_order == bond2.bond.fractional_bond_order
E   assert 0.98247694 == 0.9824771
E    +  where 0.98247694 = Bond(atom1 index=0, atom2 index=1).fractional_bond_order
E    +    where Bond(atom1 index=0, atom2 index=1) = <openff.toolkit.topology.topology.TopologyBond object at 0x7f56aba6d580>.bond
E    +  and   0.9824771 = Bond(atom1 index=0, atom2 index=1).fractional_bond_order
E    +    where Bond(atom1 index=0, atom2 index=1) = <openff.toolkit.topology.topology.TopologyBond object at 0x7f56aba6d730>.bond
```
in "`Test on ubuntu-latest, Python 3.8, RDKit=true, OpenEye=false`" even when I don't touch anything involved.

At  https://github.com/openforcefield/openff-toolkit/pull/965#issuecomment-854176024  @mattwthompson comments "this is a flaky one I've seen regularly over the past few months." @j-wags says the same in a phone call.

This prevents having a clean set of tests, and requires me double-checking every time to see if I didn't introduce some other error by accident.

The stated goal of the test is "Test that previously-defined bond orders in the topology are overwritten", and not numerical exactness of the response, so perhaps replacing it with an
```
abs(bond1.bond.fractional_bond_order - bond2.bond.fractional_bond_order) < 0.0001
```
would suffice? I do not have the knowledge to tell if my proposed patch is appropriate.

**Comment by mattwthompson** [comment]
I think a patch like that would be the right fix and should be approved. Re-reading through the test, the goal is to compare results against some **way** off totally-garbage bond orders and at least make sure that the results are somewhat similar - I don't know so much about bond order calculation methods but I suspect numerical precision is an unreasonable standard, so checking against a small difference or using something like `pytest.approx` should have been done in the first place. (I am the original author of that test, whoops.)

**Comment by adalke** [comment]
@mattwthompson  - could you confirm and merge https://github.com/openforcefield/openff-toolkit/pull/996 ?

**Comment by mattwthompson** [comment]
Fixed - thanks for getting to this
